# Matching team and member names

This notebook provides functions to match team names from the official team metadata (`team_meta_full.tsv`) with the corresponding team folders in `data/igem_team_websites/2022`. Each of these folders contains various `.txt` or `.html` files for a single team.

The main goal is to extract the raw attribution content (from either `attributions.txt` or `attributions.html`) for each team and compile it into a JSON file. The team names should be taken from `team_meta_full.tsv`. This JSON file will later be used to extract individual task attributions for each team member with LLMs. 

In the second part of this notebook, each team's roster is extracted from an API, and saved as a `.tsv` and JSON file. These names will later be given as part of the LLM prompts for extracting people and their tasks from raw attribution texts (see `9_llm_extract_names_and_task_descriptions.ipynb`).

Two resulting files from this notebook can be found on locations:
- `"../data/attributions/2022_attributions/raw_attributions_2022.json"`
- `"../data/attributions/2022_attributions/team_rosters_2022.json"`

In [1]:
import requests
import re
import difflib
import pandas as pd
from pathlib import Path
import json
from tqdm import tqdm
import subprocess

## 1. Matching Team Names

- matching webiste folder team names to team names in team meta
- extracting raw attributions for each team from their website folders

### 1.1 Save team names in lists

In [2]:
# Save the 2022 team names from team_meta_full.tsv in a list
team_meta_df = pd.read_table(
    "../data/igem_scrapping_2025/team_meta_full.tsv",
    usecols=["Team", "Year", "TeamID", "Status"]
)

teams_meta_2022 = team_meta_df[team_meta_df["Year"] == 2022]["Team"].tolist()

In [3]:
teams_meta_2022

['AFCM-Egypt',
 'AHS_Peking',
 'ASIJ_Tokyo',
 'ASU',
 'Aachen',
 'Aalto-Helsinki',
 'Aboa',
 'Aix-Marseille',
 'Alma',
 'Anatolia_College_HS',
 'AshesiGhana',
 'Athens',
 'Austin_UTexas',
 'BFSU-ICUnited',
 'BGU_Israel',
 'BIT',
 'BIT-China',
 'BJEA_China',
 'BJWZ-China',
 'BNDS_China',
 'BNSC_China',
 'BNU-China',
 'BNUZH-China',
 'BOKU-Vienna',
 'BS_United_China',
 'BUCT',
 'BUCT-China',
 'Barcelona_UB',
 'Beijing_United',
 'Bilkent_UNAM',
 'Bio-Brussels',
 'Bioplus-China',
 'Bonn-Rheinbach',
 'BostonU_HW',
 'Bulgaria',
 'CAFA_China',
 'CAU_China',
 'CCA_San_Diego',
 'CCU_Taiwan',
 'CHINA-FAFU',
 'CPU_CHINA',
 'CPU_Nanjing',
 'CSMU_Taiwan',
 'CSU_CHINA',
 'CU-Boulder',
 'CUG-China',
 'CUHK-HongKong-SBS',
 'CUHKSZ',
 'CU_Egypt',
 'Calgary',
 'Cambridge',
 'Canton_HS',
 'Chalmers-Gothenburg',
 'CityU_HongKong',
 'City_of_London_UK',
 'Concordia-Montreal',
 'Cornell',
 'Costa_Rica',
 'Crete',
 'DKU',
 'DKU_China',
 'DNHS_SanDiego_CA',
 'DTU-Denmark',
 'DUT_China',
 'DeNovoCastrians',
 'Duesseldorf',
 'Duke',
 'ECNUAS',
 'ELTE',
 'EPFL',
 'East_China',
 'East_Coast_BioCrew',
 'Edinburgh-UHAS_Ghana',
 'Estonia_TUIT',
 'Evry_Paris-Saclay',
 'Example',
 'Example_CL',
 'Example_CM',
 'Example_HS',
 'Exeter',
 'FAFU',
 'FAFU-China',
 'FDR-HB_Peru',
 'FSU',
 'Freiburg',
 'Fudan',
 'Fujian_United',
 'GA_State_SW_Jiaotong',
 'GDSYZX',
 'GEMS_Taiwan',
 'GO_Paris-Saclay',
 'GXU-China',
 'GYHS',
 'GastonDay-Shangde',
 'Goethe_Frankfurt',
 'Goettingen',
 'GreatBay_SCIE',
 'Groningen',
 'Guangxi-U-China',
 'Guelph',
 'HAGZGD-China',
 'HBUT-China',
 'HKUST',
 'HKU_HongKong',
 'HK_CPU-WYY',
 'HK_SSC',
 'HNU_China',
 'HS_China',
 'HUST-China',
 'HUS_United',
 'HZAU-China',
 'HainanU_China',
 'Harvard',
 'Heidelberg',
 'HiZJU-China',
 'Hopkins',
 'ICJFLS',
 'ICT-Mumbai',
 'IISER-Pune-India',
 'IISER-Pune2_India',
 'IISER-Tirupati_India',
 'IISER_Berhampur',
 'IISER_Bhopal',
 'IISER_Mohali',
 'IISER_TVM',
 'IISc-Bengaluru',
 'IIT-Delhi',
 'IIT_Roorkee',
 'INSA_Lyon1',
 'ITESO_Guadalajara',
 'Imperial_College_London',
 'Ionis_Paris',
 'IvyMaker-China',
 'JLU_China',
 'Jiangnan-China',
 'Jiangsu_United',
 'Jilin_China',
 'KAIT_JAPAN',
 'KCIS_Xiugang_Taipei',
 'KCL_UK',
 'KEYSTONE',
 'KUAS_Korea',
 'KU_Leuven',
 'Korea_HS',
 'LINKS_China',
 'LZU-CHINA',
 'LZU-HS-China-A',
 'LZU-HS-China-B',
 'LZU-HS-China-C',
 'LZU-HS-China-E',
 'LZU-HS-Pro-A',
 'LZU-HS-Pro-B',
 'Lambert_GA',
 'Latvia-Riga',
 'Leiden',
 'Lethbridge',
 'Lethbridge_HS',
 'Linkoping_Sweden',
 'Lund',
 'MIT',
 'MIT_MAHE',
 'MSP-Maastricht',
 'Makerere_Uganda',
 'Manchester',
 'McGill',
 'McMaster_A',
 'McMaster_Canada',
 'MiamiU',
 'Michigan',
 'MichiganState',
 'Mingdao',
 'Missouri_Miners',
 'Montpellier',
 'Munich',
 'NAU-CHINA',
 'NCHU_Taichung',
 'NCKU_Tainan',
 'NCSU',
 'NDSU',
 'NEFU_China',
 'NEU_CHINA',
 'NFLS_Nanjing',
 'NJMU-China',
 'NJTech_China',
 'NJU-China',
 'NJXDF-CHN',
 'NMU_China',
 'NNU-China',
 'NPU-CHINA',
 'NTHU_Taiwan',
 'NUDT_CHINA',
 'NU_Kazakhstan',
 'NWU-CHINA-A',
 'NYCU-Taipei',
 'NYCU_Formosa',
 'NYC_Empire_State',
 'NYU_Abu_Dhabi',
 'NYU_New_York',
 'Nanjing-China',
 'Nanjing_HS',
 'Nanjing_NFLS',
 'Navarra_BG',
 'OUC-China',
 'OhioState',
 'PINGHE',
 'PUMC_CHINA',
 'Paris_Bettencourt',
 'Patras',
 'Patras_Medicine',
 'Patras_Uni_Hellas',
 'Peking',
 'Portland',
 'PuiChing_Macau',
 'Qdai',
 'Queens_Canada',
 'RBHS_SanDiego_CA',
 'RDFZ-CHINA',
 'REC-CHENNAI',
 'RS_Joint_China',
 'RS_United_China',
 'RUBochum',
 'RUM-UPRM',
 'Rochester',
 'SCU-China',
 'SCUT-China',
 'SHBS-BANZ',
 'SHSBNU_China',
 'SHSID',
 'SJTU-BioX-Shanghai',
 'SJTU-software',
 'SMS_Shenzhen',
 'SUNY_Oneonta',
 'SUSTech_EMB',
 'SUSTech_Shenzhen',
 'SUSTech_Shenzhen_HCL',
 'SYPHU-China',
 'SYSU-CHINA',
 'SYSU-Software',
 'SZ-SHD',
 'SZPT-CHINA',
 'SZU-China',
 'Seoul_Korea',
 'Sesame_Shenzhen',
 'ShanghaiTech_China',
 'Shanghai_HS',
 'Shanghai_Metropolis',
 'Shanghai_United',
 'Shanghai_city',
 'Sheffield',
 'Shym_BIL_NIS',
 'Sogang_Korea',
 'Sorbonne_U_Paris',
 'Stanford',
 'Stockholm',
 'Stony_Brook',
 'SuZhou_Union',
 'SubCat_China',
 'SubCat_Shanghai',
 'Sydney_Australia',
 'TAMU',
 'TAU_Israel',
 'THINKER_CHINA',
 'TJUSLS_China',
 'TKS_International',
 'TU-Eindhoven',
 'TUDelft',
 'TU_Braunschweig',
 'TU_Dresden',
 'Tec-Chihuahua',
 'Tec-Monterrey',
 'TecCCM',
 'TecCEM',
 'TecMonterrey_GDL',
 'Technion-Israel',
 'Thailand_RIS',
 'TheKingsSchool_AU_HS',
 'Thessaloniki',
 'Thessaloniki_Meta',
 'Thessaly',
 'Thinker-Shenzhen',
 'Tianjin',
 'TokyoTech',
 'Tongji_China',
 'Tongji_Software',
 'Toronto',
 'Toulouse_INSA-UPS',
 'Tsinghua',
 'Tuebingen',
 'UAM',
 'UAlberta-Canada',
 'UBC-Okanagan',
 'UBC_Vancouver',
 'UCAS-China',
 'UCBerkeley',
 'UCL',
 'UCSC',
 'UChicago',
 'UConn',
 'UCopenhagen',
 'UESTC-BioTech',
 'UFMG_UFV_Brazil',
 'UFlorida',
 'UGA_Grenoble',
 'UIUC_Illinois',
 'UIncheon',
 'ULaval',
 'UMA_MALAGA',
 'UM_Macau',
 'UManitoba',
 'UMaryland',
 'UNILausanne',
 'UNSW_Australia',
 'UOregon',
 'UPNAvarra_Spain',
 'UPenn',
 'USAFA',
 'USC_Dornsife',
 'USP-EEL-Brazil',
 'USTC',
 'USTC-Software',
 'UTokyo',
 'UZurich',
 'UiOslo_Norway',
 'Uni-Hamburg',
 'Unicamp_Brazil',
 'UniofBath',
 'Uppsala',
 'VIT_Vellore',
 'Vilnius-Lithuania',
 'Virginia',
 'WHU-China',
 'WLC-Milwaukee',
 'WVHS_SanDiego',
 'WWU_Muenster',
 'Wageningen_UR',
 'Warwick',
 'Waseda_Tokyo',
 'Washington',
 'Waterloo',
 'Wego_Taipei',
 'William_and_Mary',
 'Worldshaper-HZ',
 'Worldshaper-HZBIOX',
 'Worldshaper-NJBIOX',
 'Worldshaper-Nanjing',
 'Worldshaper-Shanghai',
 'WrightState',
 'XHD-Wuhan-China',
 'XHD-Wuhan-Pro-China',
 'XJTLU-CHINA',
 'XJTU-China',
 'XMU-China',
 'Yale',
 'YiYe-China',
 'YkPaO',
 'ZJU-China',
 'ZJUT-China',
 'ZJUintl-China',
 'Zhejiang_United',
 'iBowu-China']

In [6]:
len(teams_meta_2022)

360

In [3]:
# function to save all folder names from data/igem_team_websites/2022 in a list (team_website_names_2022)
# for example, in the folder data/igem_team_websites/2022, there are folders like "aachen", "utokyo", etc., with each having attributions.txt files in them

def get_team_folder_names(base_path):
    path = Path(base_path)
    return [folder.name for folder in path.iterdir() if folder.is_dir()]

In [4]:
team_website_names_2022 = get_team_folder_names("../data/igem_team_websites/2022")

In [5]:
len(team_website_names_2022)

328

### 1.2 Match team meta and website folder names

In [7]:
# Function to set team names to lower case, remove dashes, remove all blank spaces
def clean_team_name(name):
        return name.lower().replace("-", " ").replace("_", " ").replace(" ", "").strip()

In [8]:
#Function to make a dictionary of name mappings between Team in team_meta_full.tsv and the team_website_names_2022 list 
def match_team_names(names_list_1, names_list_2):

    cleaned_2_map = {clean_team_name(name): name for name in names_list_2}

    name_map = {}
    for name1 in names_list_1:
        cleaned_name1 = clean_team_name(name1)
        matched_name = cleaned_2_map.get(cleaned_name1, "")
        name_map[name1] = matched_name

    return name_map

In [9]:
teams_names_map = match_team_names(teams_meta_2022, team_website_names_2022)

In [10]:
teams_names_map

{'AFCM-Egypt': 'afcm-egypt',
 'AHS_Peking': '',
 'ASIJ_Tokyo': 'asij-tokyo',
 'ASU': 'asu',
 'Aachen': 'aachen',
 'Aalto-Helsinki': 'aalto-helsinki',
 'Aboa': 'aboa',
 'Aix-Marseille': 'aix-marseille',
 'Alma': 'alma',
 'Anatolia_College_HS': 'anatolia-college-hs',
 'AshesiGhana': 'ashesighana',
 'Athens': 'athens',
 'Austin_UTexas': 'austin-utexas',
 'BFSU-ICUnited': 'bfsu-icunited',
 'BGU_Israel': 'bgu-israel',
 'BIT': 'bit',
 'BIT-China': 'bit-china',
 'BJEA_China': 'bjea-china',
 'BJWZ-China': 'bjwz-china',
 'BNDS_China': 'bnds-china',
 'BNSC_China': 'bnsc-china',
 'BNU-China': 'bnu-china',
 'BNUZH-China': 'bnuzh-china',
 'BOKU-Vienna': 'boku-vienna',
 'BS_United_China': 'bs-united-china',
 'BUCT': 'buct',
 'BUCT-China': 'buct-china',
 'Barcelona_UB': 'barcelona-ub',
 'Beijing_United': '',
 'Bilkent_UNAM': '',
 'Bio-Brussels': 'bio-brussels',
 'Bioplus-China': 'bioplus-china',
 'Bonn-Rheinbach': 'bonn-rheinbach',
 'BostonU_HW': 'bostonu-hw',
 'Bulgaria': 'bulgaria',
 'CAFA_China': 'cafa-china',
 'CAU_China': 'cau-china',
 'CCA_San_Diego': 'cca-san-diego',
 'CCU_Taiwan': 'ccu-taiwan',
 'CHINA-FAFU': 'china-fafu',
 'CPU_CHINA': 'cpu-china',
 'CPU_Nanjing': 'cpu-nanjing',
 'CSMU_Taiwan': 'csmu-taiwan',
 'CSU_CHINA': 'csu-china',
 'CU-Boulder': 'cu-boulder',
 'CUG-China': 'cug-china',
 'CUHK-HongKong-SBS': 'cuhk-hongkong-sbs',
 'CUHKSZ': 'cuhksz',
 'CU_Egypt': 'cu-egypt',
 'Calgary': 'calgary',
 'Cambridge': 'cambridge',
 'Canton_HS': 'canton-hs',
 'Chalmers-Gothenburg': 'chalmers-gothenburg',
 'CityU_HongKong': 'cityu-hongkong',
 'City_of_London_UK': 'city-of-london-uk',
 'Concordia-Montreal': 'concordia-montreal',
 'Cornell': 'cornell',
 'Costa_Rica': 'costa-rica',
 'Crete': 'crete',
 'DKU': 'dku',
 'DKU_China': 'dku-china',
 'DNHS_SanDiego_CA': 'dnhs-sandiego-ca',
 'DTU-Denmark': 'dtu-denmark',
 'DUT_China': 'dut-china',
 'DeNovoCastrians': 'denovocastrians',
 'Duesseldorf': 'duesseldorf',
 'Duke': 'duke',
 'ECNUAS': 'ecnuas',
 'ELTE': 'elte',
 'EPFL': 'epfl',
 'East_China': '',
 'East_Coast_BioCrew': 'east-coast-biocrew',
 'Edinburgh-UHAS_Ghana': 'edinburgh-uhas-ghana',
 'Estonia_TUIT': 'estonia-tuit',
 'Evry_Paris-Saclay': 'evry-paris-saclay',
 'Example': 'example',
 'Example_CL': 'example-cl',
 'Example_CM': 'example-cm',
 'Example_HS': 'example-hs',
 'Exeter': 'exeter',
 'FAFU': 'fafu',
 'FAFU-China': 'fafu-china',
 'FDR-HB_Peru': 'fdr-hb-peru',
 'FSU': 'fsu',
 'Freiburg': 'freiburg',
 'Fudan': 'fudan',
 'Fujian_United': 'fujian-united',
 'GA_State_SW_Jiaotong': 'ga-state-sw-jiaotong',
 'GDSYZX': 'gdsyzx',
 'GEMS_Taiwan': 'gems-taiwan',
 'GO_Paris-Saclay': 'go-paris-saclay',
 'GXU-China': 'gxu-china',
 'GYHS': 'gyhs',
 'GastonDay-Shangde': 'gastonday-shangde',
 'Goethe_Frankfurt': 'goethe-frankfurt',
 'Goettingen': 'goettingen',
 'GreatBay_SCIE': 'greatbay-scie',
 'Groningen': 'groningen',
 'Guangxi-U-China': '',
 'Guelph': 'guelph',
 'HAGZGD-China': '',
 'HBUT-China': 'hbut-china',
 'HKUST': 'hkust',
 'HKU_HongKong': 'hku-hongkong',
 'HK_CPU-WYY': 'hk-cpu-wyy',
 'HK_SSC': 'hk-ssc',
 'HNU_China': 'hnu-china',
 'HS_China': 'hs-china',
 'HUST-China': 'hust-china',
 'HUS_United': '',
 'HZAU-China': 'hzau-china',
 'HainanU_China': 'hainanu-china',
 'Harvard': 'harvard',
 'Heidelberg': 'heidelberg',
 'HiZJU-China': 'hizju-china',
 'Hopkins': 'hopkins',
 'ICJFLS': 'icjfls',
 'ICT-Mumbai': 'ict-mumbai',
 'IISER-Pune-India': 'iiser-pune-india',
 'IISER-Pune2_India': 'iiser-pune2-india',
 'IISER-Tirupati_India': 'iiser-tirupati-india',
 'IISER_Berhampur': 'iiser-berhampur',
 'IISER_Bhopal': 'iiser-bhopal',
 'IISER_Mohali': 'iiser-mohali',
 'IISER_TVM': 'iiser-tvm',
 'IISc-Bengaluru': 'iisc-bengaluru',
 'IIT-Delhi': 'iit-delhi',
 'IIT_Roorkee': 'iit-roorkee',
 'INSA_Lyon1': 'insa-lyon1',
 'ITESO_Guadalajara': '',
 'Imperial_College_London': 'imperial-college-london',
 'Ionis_Paris': 'ionis-paris',
 'IvyMaker-China': 'ivymaker-china',
 'JLU_China': 'jlu-china',
 'Jiangnan-China': 'jiangnan-china',
 'Jiangsu_United': 'jiangsu-united',
 'Jilin_China': 'jilin-china',
 'KAIT_JAPAN': 'kait-japan',
 'KCIS_Xiugang_Taipei': 'kcis-xiugang-taipei',
 'KCL_UK': 'kcl-uk',
 'KEYSTONE': 'keystone',
 'KUAS_Korea': 'kuas-korea',
 'KU_Leuven': 'ku-leuven',
 'Korea_HS': 'korea-hs',
 'LINKS_China': 'links-china',
 'LZU-CHINA': 'lzu-china',
 'LZU-HS-China-A': '',
 'LZU-HS-China-B': '',
 'LZU-HS-China-C': 'lzu-hs-china-c',
 'LZU-HS-China-E': 'lzu-hs-china-e',
 'LZU-HS-Pro-A': 'lzu-hs-pro-a',
 'LZU-HS-Pro-B': 'lzu-hs-pro-b',
 'Lambert_GA': 'lambert-ga',
 'Latvia-Riga': 'latvia-riga',
 'Leiden': 'leiden',
 'Lethbridge': 'lethbridge',
 'Lethbridge_HS': 'lethbridge-hs',
 'Linkoping_Sweden': 'linkoping-sweden',
 'Lund': 'lund',
 'MIT': 'mit',
 'MIT_MAHE': 'mit-mahe',
 'MSP-Maastricht': 'msp-maastricht',
 'Makerere_Uganda': 'makerere-uganda',
 'Manchester': 'manchester',
 'McGill': '',
 'McMaster_A': 'mcmaster-a',
 'McMaster_Canada': 'mcmaster-canada',
 'MiamiU': 'miamiu',
 'Michigan': 'michigan',
 'MichiganState': 'michiganstate',
 'Mingdao': 'mingdao',
 'Missouri_Miners': 'missouri-miners',
 'Montpellier': 'montpellier',
 'Munich': 'munich',
 'NAU-CHINA': 'nau-china',
 'NCHU_Taichung': 'nchu-taichung',
 'NCKU_Tainan': 'ncku-tainan',
 'NCSU': '',
 'NDSU': 'ndsu',
 'NEFU_China': 'nefu-china',
 'NEU_CHINA': 'neu-china',
 'NFLS_Nanjing': 'nfls-nanjing',
 'NJMU-China': 'njmu-china',
 'NJTech_China': 'njtech-china',
 'NJU-China': 'nju-china',
 'NJXDF-CHN': '',
 'NMU_China': 'nmu-china',
 'NNU-China': 'nnu-china',
 'NPU-CHINA': 'npu-china',
 'NTHU_Taiwan': 'nthu-taiwan',
 'NUDT_CHINA': 'nudt-china',
 'NU_Kazakhstan': 'nu-kazakhstan',
 'NWU-CHINA-A': 'nwu-china-a',
 'NYCU-Taipei': 'nycu-taipei',
 'NYCU_Formosa': 'nycu-formosa',
 'NYC_Empire_State': 'nyc-empire-state',
 'NYU_Abu_Dhabi': 'nyu-abu-dhabi',
 'NYU_New_York': '',
 'Nanjing-China': 'nanjing-china',
 'Nanjing_HS': 'nanjing-hs',
 'Nanjing_NFLS': 'nanjing-nfls',
 'Navarra_BG': 'navarra-bg',
 'OUC-China': 'ouc-china',
 'OhioState': 'ohiostate',
 'PINGHE': '',
 'PUMC_CHINA': 'pumc-china',
 'Paris_Bettencourt': 'paris-bettencourt',
 'Patras': 'patras',
 'Patras_Medicine': 'patras-medicine',
 'Patras_Uni_Hellas': 'patras-uni-hellas',
 'Peking': 'peking',
 'Portland': 'portland',
 'PuiChing_Macau': 'puiching-macau',
 'Qdai': 'qdai',
 'Queens_Canada': 'queens-canada',
 'RBHS_SanDiego_CA': 'rbhs-sandiego-ca',
 'RDFZ-CHINA': 'rdfz-china',
 'REC-CHENNAI': 'rec-chennai',
 'RS_Joint_China': '',
 'RS_United_China': 'rs-united-china',
 'RUBochum': 'rubochum',
 'RUM-UPRM': 'rum-uprm',
 'Rochester': 'rochester',
 'SCU-China': 'scu-china',
 'SCUT-China': 'scut-china',
 'SHBS-BANZ': '',
 'SHSBNU_China': 'shsbnu-china',
 'SHSID': '',
 'SJTU-BioX-Shanghai': 'sjtu-biox-shanghai',
 'SJTU-software': 'sjtu-software',
 'SMS_Shenzhen': 'sms-shenzhen',
 'SUNY_Oneonta': 'suny-oneonta',
 'SUSTech_EMB': 'sustech-emb',
 'SUSTech_Shenzhen': 'sustech-shenzhen',
 'SUSTech_Shenzhen_HCL': '',
 'SYPHU-China': '',
 'SYSU-CHINA': 'sysu-china',
 'SYSU-Software': '',
 'SZ-SHD': 'sz-shd',
 'SZPT-CHINA': 'szpt-china',
 'SZU-China': 'szu-china',
 'Seoul_Korea': 'seoul-korea',
 'Sesame_Shenzhen': 'sesame-shenzhen',
 'ShanghaiTech_China': 'shanghaitech-china',
 'Shanghai_HS': 'shanghai-hs',
 'Shanghai_Metropolis': 'shanghai-metropolis',
 'Shanghai_United': '',
 'Shanghai_city': 'shanghai-city',
 'Sheffield': 'sheffield',
 'Shym_BIL_NIS': 'shym-bil-nis',
 'Sogang_Korea': 'sogang-korea',
 'Sorbonne_U_Paris': 'sorbonne-u-paris',
 'Stanford': 'stanford',
 'Stockholm': 'stockholm',
 'Stony_Brook': 'stony-brook',
 'SuZhou_Union': '',
 'SubCat_China': 'subcat-china',
 'SubCat_Shanghai': 'subcat-shanghai',
 'Sydney_Australia': 'sydney-australia',
 'TAMU': 'tamu',
 'TAU_Israel': 'tau-israel',
 'THINKER_CHINA': 'thinker-china',
 'TJUSLS_China': 'tjusls-china',
 'TKS_International': '',
 'TU-Eindhoven': 'tu-eindhoven',
 'TUDelft': 'tudelft',
 'TU_Braunschweig': 'tu-braunschweig',
 'TU_Dresden': 'tu-dresden',
 'Tec-Chihuahua': 'tec-chihuahua',
 'Tec-Monterrey': 'tec-monterrey',
 'TecCCM': 'tecccm',
 'TecCEM': 'teccem',
 'TecMonterrey_GDL': 'tecmonterrey-gdl',
 'Technion-Israel': 'technion-israel',
 'Thailand_RIS': 'thailand-ris',
 'TheKingsSchool_AU_HS': 'thekingsschool-au-hs',
 'Thessaloniki': 'thessaloniki',
 'Thessaloniki_Meta': 'thessaloniki-meta',
 'Thessaly': 'thessaly',
 'Thinker-Shenzhen': 'thinker-shenzhen',
 'Tianjin': 'tianjin',
 'TokyoTech': 'tokyotech',
 'Tongji_China': 'tongji-china',
 'Tongji_Software': 'tongji-software',
 'Toronto': 'toronto',
 'Toulouse_INSA-UPS': 'toulouse-insa-ups',
 'Tsinghua': 'tsinghua',
 'Tuebingen': 'tuebingen',
 'UAM': 'uam',
 'UAlberta-Canada': '',
 'UBC-Okanagan': 'ubc-okanagan',
 'UBC_Vancouver': 'ubc-vancouver',
 'UCAS-China': 'ucas-china',
 'UCBerkeley': '',
 'UCL': 'ucl',
 'UCSC': 'ucsc',
 'UChicago': 'uchicago',
 'UConn': '',
 'UCopenhagen': 'ucopenhagen',
 'UESTC-BioTech': 'uestc-biotech',
 'UFMG_UFV_Brazil': 'ufmg-ufv-brazil',
 'UFlorida': 'uflorida',
 'UGA_Grenoble': '',
 'UIUC_Illinois': 'uiuc-illinois',
 'UIncheon': 'uincheon',
 'ULaval': 'ulaval',
 'UMA_MALAGA': 'uma-malaga',
 'UM_Macau': 'um-macau',
 'UManitoba': 'umanitoba',
 'UMaryland': 'umaryland',
 'UNILausanne': 'unilausanne',
 'UNSW_Australia': 'unsw-australia',
 'UOregon': 'uoregon',
 'UPNAvarra_Spain': 'upnavarra-spain',
 'UPenn': 'upenn',
 'USAFA': '',
 'USC_Dornsife': 'usc-dornsife',
 'USP-EEL-Brazil': 'usp-eel-brazil',
 'USTC': 'ustc',
 'USTC-Software': 'ustc-software',
 'UTokyo': 'utokyo',
 'UZurich': 'uzurich',
 'UiOslo_Norway': 'uioslo-norway',
 'Uni-Hamburg': 'uni-hamburg',
 'Unicamp_Brazil': 'unicamp-brazil',
 'UniofBath': 'uniofbath',
 'Uppsala': 'uppsala',
 'VIT_Vellore': 'vit-vellore',
 'Vilnius-Lithuania': 'vilnius-lithuania',
 'Virginia': 'virginia',
 'WHU-China': '',
 'WLC-Milwaukee': 'wlc-milwaukee',
 'WVHS_SanDiego': 'wvhs-sandiego',
 'WWU_Muenster': 'wwu-muenster',
 'Wageningen_UR': 'wageningen-ur',
 'Warwick': 'warwick',
 'Waseda_Tokyo': 'waseda-tokyo',
 'Washington': 'washington',
 'Waterloo': 'waterloo',
 'Wego_Taipei': 'wego-taipei',
 'William_and_Mary': 'william-and-mary',
 'Worldshaper-HZ': 'worldshaper-hz',
 'Worldshaper-HZBIOX': '',
 'Worldshaper-NJBIOX': '',
 'Worldshaper-Nanjing': 'worldshaper-nanjing',
 'Worldshaper-Shanghai': 'worldshaper-shanghai',
 'WrightState': 'wrightstate',
 'XHD-Wuhan-China': 'xhd-wuhan-china',
 'XHD-Wuhan-Pro-China': 'xhd-wuhan-pro-china',
 'XJTLU-CHINA': 'xjtlu-china',
 'XJTU-China': 'xjtu-china',
 'XMU-China': 'xmu-china',
 'Yale': 'yale',
 'YiYe-China': 'yiye-china',
 'YkPaO': 'ykpao',
 'ZJU-China': 'zju-china',
 'ZJUT-China': 'zjut-china',
 'ZJUintl-China': 'zjuintl-china',
 'Zhejiang_United': 'zhejiang-united',
 'iBowu-China': 'ibowu-china'}

In [ ]:
# Teams from the website folders that do not match any team from the team_meta_full.tsv
unmatched_names_from_websites = [k for k in teams_names_map if k == '']
len(unmatched_names_from_websites)

0

In [ ]:
# Teams from the team_meta_full.tsv that do not match any team from the website folders
unmatched_names_from_meta = [k for k, v in teams_names_map.items() if v == ""]
len(unmatched_names_from_meta)

32

In [22]:
# Dataframe of unmatched team names and their status from 
unmatched_df = team_meta_df[
    (team_meta_df["Year"] == 2022) &
    (team_meta_df["Team"].isin(unmatched_names_from_meta))
]

unmatched_df = unmatched_df[["Team", "Status"]]

unmatched_df

                      Team        Status
20              AHS_Peking     withdrawn
398         Beijing_United  disqualified
434           Bilkent_UNAM     withdrawn
1016            East_China  disqualified
1362       Guangxi-U-China  disqualified
1383          HAGZGD-China     withdrawn
1516            HUS_United  disqualified
1802     ITESO_Guadalajara      accepted
2067        LZU-HS-China-A  disqualified
2068        LZU-HS-China-B  disqualified
2293                McGill      accepted
2469                  NCSU     withdrawn
2557             NJXDF-CHN  disqualified
2724          NYU_New_York     withdrawn
2882                PINGHE  disqualified
3103        RS_Joint_China  disqualified
3243             SHBS-BANZ  disqualified
3258                 SHSID  disqualified
3361  SUSTech_Shenzhen_HCL     withdrawn
3371           SYPHU-China     withdrawn
3398         SYSU-Software      accepted
3489       Shanghai_United  disqualified
3635          SuZhou_Union  disqualified
3718     TKS_International     withdrawn
4079       UAlberta-Canada     withdrawn
4108            UCBerkeley     withdrawn
4213                 UConn     withdrawn
4266          UGA_Grenoble     withdrawn
4451                 USAFA      accepted
4745             WHU-China  disqualified
4913    Worldshaper-HZBIOX  disqualified
4914    Worldshaper-NJBIOX  disqualified

In [23]:
unmatched_df["Status"].value_counts()

Status
disqualified    16
withdrawn       12
accepted         4
Name: count, dtype: int64


There are 32 more teams listed in `team_meta_full.tsv` than there are folders in `igem_team_websites/2022`. On the other hand, every team found in the `igem_team_websites/2022` folder also exists in `team_meta_full.tsv` (they have the same normalized names). Out of the 32 missing teams, 28 of them are either withdrawn or disqualified which explains the absence of their attributions folder. Four of them were accepted for the Jamboree, but they do not contain an attributions folder in `igem_team_websites/2022`. One of such teams is present in the 2022 survey, so its raw attributions will be extracted manually since it is more time-efficient for a single case.

### 1.3 Saving attributions data per each team

In [14]:
# Function to make a json file of all teams and their attributions txt files
no_attributions_teams = []

def collect_attributions_texts(base_path, output_json_path):
    base = Path(base_path)
    team_attributions = []

    for team_folder in sorted(base.iterdir(), key=lambda x: x.name.lower()):
        if not team_folder.is_dir():
            continue

        attributions_file = team_folder / "attributions.txt"
        fallback_file = team_folder / "attributions.html.txt"
        # some teams have attributions.html.txt files instead of attributions.txt

        if attributions_file.exists():
            file_to_read = attributions_file
        elif fallback_file.exists():
            file_to_read = fallback_file
        else:
            print(f"No attributions file found for team: {team_folder.name}")
            no_attributions_teams.append(team_folder.name)
            continue

        try:
            content = file_to_read.read_text(encoding="utf-8").strip()
            team_attributions.append({
                "teamName": team_folder.name,
                "attributionsText": content
            })
        except Exception as e:
            print(f"Error reading {file_to_read.name} for team {team_folder.name}: {e}")

    with open(output_json_path, "w", encoding="utf-8") as f:
        json.dump(team_attributions, f, ensure_ascii=False, indent=2)

    print(f"Raw team attributions website texts saved to {output_json_path}")

In [15]:
collect_attributions_texts(
    base_path="../data/igem_team_websites/2022",
    output_json_path="../data/attributions/2022_attributions/raw_attributions_2022.json"
)

No attributions file found for team: bgu-israel
No attributions file found for team: bnds-china
No attributions file found for team: city-of-london-uk
No attributions file found for team: fudan
No attributions file found for team: gdsyzx
No attributions file found for team: hku-hongkong
No attributions file found for team: iit-roorkee
No attributions file found for team: nju-china
No attributions file found for team: patras-medicine
No attributions file found for team: peking
No attributions file found for team: queens-canada
No attributions file found for team: stanford
No attributions file found for team: sysu-china
No attributions file found for team: thailand-ris
No attributions file found for team: tongji-software
No attributions file found for team: vilnius-lithuania
No attributions file found for team: yale
Raw team attributions website texts saved to ../data/attributions/2022_attributions/raw_attributions_2022.json

In [16]:
no_attributions_teams

['bgu-israel',
 'bnds-china',
 'city-of-london-uk',
 'fudan',
 'gdsyzx',
 'hku-hongkong',
 'iit-roorkee',
 'nju-china',
 'patras-medicine',
 'peking',
 'queens-canada',
 'stanford',
 'sysu-china',
 'thailand-ris',
 'tongji-software',
 'vilnius-lithuania',
 'yale']

In [ ]:
# Teams with no attribution files

team_meta_2022 = team_meta_df[team_meta_df['Year'] == 2022].copy() #so the names are the same as they were in 2022

team_meta_2022['Team_normalized'] = team_meta_2022['Team'].apply(clean_team_name)

normalized_no_attr = [clean_team_name(name) for name in no_attributions_teams]

df_no_attr = team_meta_2022[
    team_meta_2022['Team_normalized'].isin(normalized_no_attr)
].drop_duplicates(subset=['Team_normalized'])

df_no_attr_status = df_no_attr[['Team', 'Status']]

df_no_attr_status

                   Team    Status
225          BGU_Israel  accepted
296          BNDS_China  accepted
781   City_of_London_UK  accepted
1189              Fudan  accepted
1213             GDSYZX  accepted
1448       HKU_HongKong  accepted
1772        IIT_Roorkee  accepted
2550          NJU-China  accepted
2933    Patras_Medicine  accepted
2946             Peking  accepted
3066      Queens_Canada  accepted
3380         SYSU-CHINA  accepted
3591           Stanford  accepted
3865       Thailand_RIS  accepted
3957    Tongji_Software  accepted
4694  Vilnius-Lithuania  accepted
5001               Yale  accepted

There are 17 teams that do not have an `attributions.txt` or `attributions.html` file, but all of them were officially accepted. After checking their GitLab repositories, it was found that all of them do contain attributions information, although most of it is written in JavaScript. This explains why Rathin’s previous text extraction process skipped these teams. Since only 5 of such teams also appear in the survey, their raw attribution text, as well as each member’s task descriptions, will be extracted manually.

In [19]:
# Replace team names in the json file with the correct ones from the name map (gathered from team meta)

with open("../data/attributions/2022_attributions/raw_attributions_2022.json", "r", encoding="utf-8") as f:
    data = json.load(f)

# Take the keys from teams_names_map as correct name formats
reversed_map = {v: k for k, v in teams_names_map.items() if v}

for entry in data:
    original_name = entry["teamName"]
    corrected_name = reversed_map.get(original_name, original_name)
    entry["teamName"] = corrected_name

# Overwrite the original json file
with open("../data/attributions/2022_attributions/raw_attributions_2022.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

In [20]:
# Read raw attributions json file and create a DataFrame
with open("../data/attributions/2022_attributions/raw_attributions_2022.json", "r", encoding="utf-8") as f:
    attributions_data = json.load(f)
raw_attributions_df = pd.DataFrame(attributions_data)

raw_attributions_df

            teamName                                   attributionsText
0             Aachen  Project\nDescription Contribution Engineering ...
1     Aalto-Helsinki  Home\nProject\nProject\nDescription\nImplement...
2               Aboa  Home\nAbout us\nTeam members\nAttributions\nCo...
3         AFCM-Egypt  Home\nTeam\nContribution Attributions Team mem...
4      Aix-Marseille  Aix-Marseille\nHome\nTeam\nTeam\nAttributions\...
..               ...                                                ...
306            YkPaO  ProTeen-fessionals\nHome\nTeam\nTeam\nAttribut...
307  Zhejiang_United  MaiaPotion\nAwards\nEducation\nEntrepreneurshi...
308        ZJU-China  TEAM\nMember\nAttributions\nPartnership\nColla...
309    ZJUintl-China  Home\nTeam\nTeam\nAttributions\nProject\nDescr...
310       ZJUT-China  Home\nTeam\nTeam\nAttributions\nCollaborations...

[311 rows x 2 columns]

## 2. Extracting Member Names and Tasks

- extracting member names from team roster API

In [ ]:
# Save the 2022 team names and their IDs from team_meta_full.tsv in a list of team dictionaries (to be used in roster API calls)
# Each dictionary will have the keys "teamName" and "teamID" 

teams_2022_df = team_meta_df[team_meta_df["Year"] == 2022]

teams_names_ids_2022 = teams_2022_df.rename(columns={"Team": "teamName", "TeamID": "teamID", "Year": "year"})[
    ["teamName", "teamID", "year"]
].to_dict(orient="records")

teams_names_ids_2022

[{'teamName': 'AFCM-Egypt', 'teamID': 4140, 'year': 2022},
 {'teamName': 'AHS_Peking', 'teamID': 4396, 'year': 2022},
 {'teamName': 'ASIJ_Tokyo', 'teamID': 4334, 'year': 2022},
 {'teamName': 'ASU', 'teamID': 4455, 'year': 2022},
 {'teamName': 'Aachen', 'teamID': 4138, 'year': 2022},
 {'teamName': 'Aalto-Helsinki', 'teamID': 4159, 'year': 2022},
 {'teamName': 'Aboa', 'teamID': 4207, 'year': 2022},
 {'teamName': 'Aix-Marseille', 'teamID': 4189, 'year': 2022},
 {'teamName': 'Alma', 'teamID': 4166, 'year': 2022},
 {'teamName': 'Anatolia_College_HS', 'teamID': 4503, 'year': 2022},
 {'teamName': 'AshesiGhana', 'teamID': 4186, 'year': 2022},
 {'teamName': 'Athens', 'teamID': 4294, 'year': 2022},
 {'teamName': 'Austin_UTexas', 'teamID': 4342, 'year': 2022},
 {'teamName': 'BFSU-ICUnited', 'teamID': 4400, 'year': 2022},
 {'teamName': 'BGU_Israel', 'teamID': 4120, 'year': 2022},
 {'teamName': 'BIT', 'teamID': 4128, 'year': 2022},
 {'teamName': 'BIT-China', 'teamID': 4232, 'year': 2022},
 {'teamName': 'BJEA_China', 'teamID': 4221, 'year': 2022},
 {'teamName': 'BJWZ-China', 'teamID': 4203, 'year': 2022},
 {'teamName': 'BNDS_China', 'teamID': 4204, 'year': 2022},
 {'teamName': 'BNSC_China', 'teamID': 4237, 'year': 2022},
 {'teamName': 'BNU-China', 'teamID': 4117, 'year': 2022},
 {'teamName': 'BNUZH-China', 'teamID': 4211, 'year': 2022},
 {'teamName': 'BOKU-Vienna', 'teamID': 4423, 'year': 2022},
 {'teamName': 'BS_United_China', 'teamID': 4329, 'year': 2022},
 {'teamName': 'BUCT', 'teamID': 4146, 'year': 2022},
 {'teamName': 'BUCT-China', 'teamID': 4194, 'year': 2022},
 {'teamName': 'Barcelona_UB', 'teamID': 4501, 'year': 2022},
 {'teamName': 'Beijing_United', 'teamID': 4290, 'year': 2022},
 {'teamName': 'Bilkent_UNAM', 'teamID': 4476, 'year': 2022},
 {'teamName': 'Bio-Brussels', 'teamID': 4403, 'year': 2022},
 {'teamName': 'Bioplus-China', 'teamID': 4413, 'year': 2022},
 {'teamName': 'Bonn-Rheinbach', 'teamID': 4510, 'year': 2022},
 {'teamName': 'BostonU_HW', 'teamID': 4485, 'year': 2022},
 {'teamName': 'Bulgaria', 'teamID': 4364, 'year': 2022},
 {'teamName': 'CAFA_China', 'teamID': 4226, 'year': 2022},
 {'teamName': 'CAU_China', 'teamID': 4192, 'year': 2022},
 {'teamName': 'CCA_San_Diego', 'teamID': 4261, 'year': 2022},
 {'teamName': 'CCU_Taiwan', 'teamID': 4131, 'year': 2022},
 {'teamName': 'CHINA-FAFU', 'teamID': 4112, 'year': 2022},
 {'teamName': 'CPU_CHINA', 'teamID': 4308, 'year': 2022},
 {'teamName': 'CPU_Nanjing', 'teamID': 4257, 'year': 2022},
 {'teamName': 'CSMU_Taiwan', 'teamID': 4151, 'year': 2022},
 {'teamName': 'CSU_CHINA', 'teamID': 4127, 'year': 2022},
 {'teamName': 'CU-Boulder', 'teamID': 4201, 'year': 2022},
 {'teamName': 'CUG-China', 'teamID': 4242, 'year': 2022},
 {'teamName': 'CUHK-HongKong-SBS', 'teamID': 4469, 'year': 2022},
 {'teamName': 'CUHKSZ', 'teamID': 4459, 'year': 2022},
 {'teamName': 'CU_Egypt', 'teamID': 4165, 'year': 2022},
 {'teamName': 'Calgary', 'teamID': 4437, 'year': 2022},
 {'teamName': 'Cambridge', 'teamID': 4491, 'year': 2022},
 {'teamName': 'Canton_HS', 'teamID': 4291, 'year': 2022},
 {'teamName': 'Chalmers-Gothenburg', 'teamID': 4367, 'year': 2022},
 {'teamName': 'CityU_HongKong', 'teamID': 4154, 'year': 2022},
 {'teamName': 'City_of_London_UK', 'teamID': 4508, 'year': 2022},
 {'teamName': 'Concordia-Montreal', 'teamID': 4136, 'year': 2022},
 {'teamName': 'Cornell', 'teamID': 4322, 'year': 2022},
 {'teamName': 'Costa_Rica', 'teamID': 4133, 'year': 2022},
 {'teamName': 'Crete', 'teamID': 4495, 'year': 2022},
 {'teamName': 'DKU', 'teamID': 4161, 'year': 2022},
 {'teamName': 'DKU_China', 'teamID': 4494, 'year': 2022},
 {'teamName': 'DNHS_SanDiego_CA', 'teamID': 4386, 'year': 2022},
 {'teamName': 'DTU-Denmark', 'teamID': 4129, 'year': 2022},
 {'teamName': 'DUT_China', 'teamID': 4176, 'year': 2022},
 {'teamName': 'DeNovoCastrians', 'teamID': 4431, 'year': 2022},
 {'teamName': 'Duesseldorf', 'teamID': 4369, 'year': 2022},
 {'teamName': 'Duke', 'teamID': 4234, 'year': 2022},
 {'teamName': 'ECNUAS', 'teamID': 4281, 'year': 2022},
 {'teamName': 'ELTE', 'teamID': 4375, 'year': 2022},
 {'teamName': 'EPFL', 'teamID': 4439, 'year': 2022},
 {'teamName': 'East_China', 'teamID': 4515, 'year': 2022},
 {'teamName': 'East_Coast_BioCrew', 'teamID': 4458, 'year': 2022},
 {'teamName': 'Edinburgh-UHAS_Ghana', 'teamID': 4390, 'year': 2022},
 {'teamName': 'Estonia_TUIT', 'teamID': 4440, 'year': 2022},
 {'teamName': 'Evry_Paris-Saclay', 'teamID': 4432, 'year': 2022},
 {'teamName': 'Example', 'teamID': 4108, 'year': 2022},
 {'teamName': 'Example_CL', 'teamID': 4111, 'year': 2022},
 {'teamName': 'Example_CM', 'teamID': 4110, 'year': 2022},
 {'teamName': 'Example_HS', 'teamID': 4109, 'year': 2022},
 {'teamName': 'Exeter', 'teamID': 4339, 'year': 2022},
 {'teamName': 'FAFU', 'teamID': 4253, 'year': 2022},
 {'teamName': 'FAFU-China', 'teamID': 4113, 'year': 2022},
 {'teamName': 'FDR-HB_Peru', 'teamID': 4338, 'year': 2022},
 {'teamName': 'FSU', 'teamID': 4475, 'year': 2022},
 {'teamName': 'Freiburg', 'teamID': 4229, 'year': 2022},
 {'teamName': 'Fudan', 'teamID': 4162, 'year': 2022},
 {'teamName': 'Fujian_United', 'teamID': 4288, 'year': 2022},
 {'teamName': 'GA_State_SW_Jiaotong', 'teamID': 4493, 'year': 2022},
 {'teamName': 'GDSYZX', 'teamID': 4270, 'year': 2022},
 {'teamName': 'GEMS_Taiwan', 'teamID': 4137, 'year': 2022},
 {'teamName': 'GO_Paris-Saclay', 'teamID': 4370, 'year': 2022},
 {'teamName': 'GXU-China', 'teamID': 4354, 'year': 2022},
 {'teamName': 'GYHS', 'teamID': 4430, 'year': 2022},
 {'teamName': 'GastonDay-Shangde', 'teamID': 4481, 'year': 2022},
 {'teamName': 'Goethe_Frankfurt', 'teamID': 4285, 'year': 2022},
 {'teamName': 'Goettingen', 'teamID': 4404, 'year': 2022},
 {'teamName': 'GreatBay_SCIE', 'teamID': 4275, 'year': 2022},
 {'teamName': 'Groningen', 'teamID': 4233, 'year': 2022},
 {'teamName': 'Guangxi-U-China', 'teamID': 4157, 'year': 2022},
 {'teamName': 'Guelph', 'teamID': 4321, 'year': 2022},
 {'teamName': 'HAGZGD-China', 'teamID': 4489, 'year': 2022},
 {'teamName': 'HBUT-China', 'teamID': 4249, 'year': 2022},
 {'teamName': 'HKUST', 'teamID': 4225, 'year': 2022},
 {'teamName': 'HKU_HongKong', 'teamID': 4241, 'year': 2022},
 {'teamName': 'HK_CPU-WYY', 'teamID': 4126, 'year': 2022},
 {'teamName': 'HK_SSC', 'teamID': 4384, 'year': 2022},
 {'teamName': 'HNU_China', 'teamID': 4252, 'year': 2022},
 {'teamName': 'HS_China', 'teamID': 4183, 'year': 2022},
 {'teamName': 'HUST-China', 'teamID': 4468, 'year': 2022},
 {'teamName': 'HUS_United', 'teamID': 4511, 'year': 2022},
 {'teamName': 'HZAU-China', 'teamID': 4169, 'year': 2022},
 {'teamName': 'HainanU_China', 'teamID': 4223, 'year': 2022},
 {'teamName': 'Harvard', 'teamID': 4480, 'year': 2022},
 {'teamName': 'Heidelberg', 'teamID': 4344, 'year': 2022},
 {'teamName': 'HiZJU-China', 'teamID': 4177, 'year': 2022},
 {'teamName': 'Hopkins', 'teamID': 4452, 'year': 2022},
 {'teamName': 'ICJFLS', 'teamID': 4167, 'year': 2022},
 {'teamName': 'ICT-Mumbai', 'teamID': 4303, 'year': 2022},
 {'teamName': 'IISER-Pune-India', 'teamID': 4392, 'year': 2022},
 {'teamName': 'IISER-Pune2_India', 'teamID': 4429, 'year': 2022},
 {'teamName': 'IISER-Tirupati_India', 'teamID': 4438, 'year': 2022},
 {'teamName': 'IISER_Berhampur', 'teamID': 4449, 'year': 2022},
 {'teamName': 'IISER_Bhopal', 'teamID': 4382, 'year': 2022},
 {'teamName': 'IISER_Mohali', 'teamID': 4391, 'year': 2022},
 {'teamName': 'IISER_TVM', 'teamID': 4359, 'year': 2022},
 {'teamName': 'IISc-Bengaluru', 'teamID': 4462, 'year': 2022},
 {'teamName': 'IIT-Delhi', 'teamID': 4428, 'year': 2022},
 {'teamName': 'IIT_Roorkee', 'teamID': 4434, 'year': 2022},
 {'teamName': 'INSA_Lyon1', 'teamID': 4239, 'year': 2022},
 {'teamName': 'ITESO_Guadalajara', 'teamID': 4424, 'year': 2022},
 {'teamName': 'Imperial_College_London', 'teamID': 4212, 'year': 2022},
 {'teamName': 'Ionis_Paris', 'teamID': 4187, 'year': 2022},
 {'teamName': 'IvyMaker-China', 'teamID': 4122, 'year': 2022},
 {'teamName': 'JLU_China', 'teamID': 4427, 'year': 2022},
 {'teamName': 'Jiangnan-China', 'teamID': 4149, 'year': 2022},
 {'teamName': 'Jiangsu_United', 'teamID': 4516, 'year': 2022},
 {'teamName': 'Jilin_China', 'teamID': 4385, 'year': 2022},
 {'teamName': 'KAIT_JAPAN', 'teamID': 4487, 'year': 2022},
 {'teamName': 'KCIS_Xiugang_Taipei', 'teamID': 4180, 'year': 2022},
 {'teamName': 'KCL_UK', 'teamID': 4388, 'year': 2022},
 {'teamName': 'KEYSTONE', 'teamID': 4274, 'year': 2022},
 {'teamName': 'KUAS_Korea', 'teamID': 4371, 'year': 2022},
 {'teamName': 'KU_Leuven', 'teamID': 4345, 'year': 2022},
 {'teamName': 'Korea_HS', 'teamID': 4305, 'year': 2022},
 {'teamName': 'LINKS_China', 'teamID': 4273, 'year': 2022},
 {'teamName': 'LZU-CHINA', 'teamID': 4156, 'year': 2022},
 {'teamName': 'LZU-HS-China-A', 'teamID': 4330, 'year': 2022},
 {'teamName': 'LZU-HS-China-B', 'teamID': 4331, 'year': 2022},
 {'teamName': 'LZU-HS-China-C', 'teamID': 4332, 'year': 2022},
 {'teamName': 'LZU-HS-China-E', 'teamID': 4512, 'year': 2022},
 {'teamName': 'LZU-HS-Pro-A', 'teamID': 4300, 'year': 2022},
 {'teamName': 'LZU-HS-Pro-B', 'teamID': 4301, 'year': 2022},
 {'teamName': 'Lambert_GA', 'teamID': 4245, 'year': 2022},
 {'teamName': 'Latvia-Riga', 'teamID': 4398, 'year': 2022},
 {'teamName': 'Leiden', 'teamID': 4259, 'year': 2022},
 {'teamName': 'Lethbridge', 'teamID': 4139, 'year': 2022},
 {'teamName': 'Lethbridge_HS', 'teamID': 4351, 'year': 2022},
 {'teamName': 'Linkoping_Sweden', 'teamID': 4433, 'year': 2022},
 {'teamName': 'Lund', 'teamID': 4373, 'year': 2022},
 {'teamName': 'MIT', 'teamID': 4320, 'year': 2022},
 {'teamName': 'MIT_MAHE', 'teamID': 4200, 'year': 2022},
 {'teamName': 'MSP-Maastricht', 'teamID': 4185, 'year': 2022},
 {'teamName': 'Makerere_Uganda', 'teamID': 4517, 'year': 2022},
 {'teamName': 'Manchester', 'teamID': 4123, 'year': 2022},
 {'teamName': 'McGill', 'teamID': 4348, 'year': 2022},
 {'teamName': 'McMaster_A', 'teamID': 4415, 'year': 2022},
 {'teamName': 'McMaster_Canada', 'teamID': 4442, 'year': 2022},
 {'teamName': 'MiamiU', 'teamID': 4514, 'year': 2022},
 {'teamName': 'Michigan', 'teamID': 4143, 'year': 2022},
 {'teamName': 'MichiganState', 'teamID': 4135, 'year': 2022},
 {'teamName': 'Mingdao', 'teamID': 4150, 'year': 2022},
 {'teamName': 'Missouri_Miners', 'teamID': 4262, 'year': 2022},
 {'teamName': 'Montpellier', 'teamID': 4473, 'year': 2022},
 {'teamName': 'Munich', 'teamID': 4497, 'year': 2022},
 {'teamName': 'NAU-CHINA', 'teamID': 4164, 'year': 2022},
 {'teamName': 'NCHU_Taichung', 'teamID': 4358, 'year': 2022},
 {'teamName': 'NCKU_Tainan', 'teamID': 4171, 'year': 2022},
 {'teamName': 'NCSU', 'teamID': 4446, 'year': 2022},
 {'teamName': 'NDSU', 'teamID': 4258, 'year': 2022},
 {'teamName': 'NEFU_China', 'teamID': 4121, 'year': 2022},
 {'teamName': 'NEU_CHINA', 'teamID': 4220, 'year': 2022},
 {'teamName': 'NFLS_Nanjing', 'teamID': 4376, 'year': 2022},
 {'teamName': 'NJMU-China', 'teamID': 4205, 'year': 2022},
 {'teamName': 'NJTech_China', 'teamID': 4119, 'year': 2022},
 {'teamName': 'NJU-China', 'teamID': 4173, 'year': 2022},
 {'teamName': 'NJXDF-CHN', 'teamID': 4297, 'year': 2022},
 {'teamName': 'NMU_China', 'teamID': 4421, 'year': 2022},
 {'teamName': 'NNU-China', 'teamID': 4343, 'year': 2022},
 {'teamName': 'NPU-CHINA', 'teamID': 4309, 'year': 2022},
 {'teamName': 'NTHU_Taiwan', 'teamID': 4336, 'year': 2022},
 {'teamName': 'NUDT_CHINA', 'teamID': 4414, 'year': 2022},
 {'teamName': 'NU_Kazakhstan', 'teamID': 4389, 'year': 2022},
 {'teamName': 'NWU-CHINA-A', 'teamID': 4199, 'year': 2022},
 {'teamName': 'NYCU-Taipei', 'teamID': 4461, 'year': 2022},
 {'teamName': 'NYCU_Formosa', 'teamID': 4377, 'year': 2022},
 {'teamName': 'NYC_Empire_State', 'teamID': 4482, 'year': 2022},
 {'teamName': 'NYU_Abu_Dhabi', 'teamID': 4397, 'year': 2022},
 {'teamName': 'NYU_New_York', 'teamID': 4478, 'year': 2022},
 {'teamName': 'Nanjing-China', 'teamID': 4134, 'year': 2022},
 {'teamName': 'Nanjing_HS', 'teamID': 4289, 'year': 2022},
 {'teamName': 'Nanjing_NFLS', 'teamID': 4125, 'year': 2022},
 {'teamName': 'Navarra_BG', 'teamID': 4374, 'year': 2022},
 {'teamName': 'OUC-China', 'teamID': 4193, 'year': 2022},
 {'teamName': 'OhioState', 'teamID': 4341, 'year': 2022},
 {'teamName': 'PINGHE', 'teamID': 4284, 'year': 2022},
 {'teamName': 'PUMC_CHINA', 'teamID': 4318, 'year': 2022},
 {'teamName': 'Paris_Bettencourt', 'teamID': 4216, 'year': 2022},
 {'teamName': 'Patras', 'teamID': 4287, 'year': 2022},
 {'teamName': 'Patras_Medicine', 'teamID': 4118, 'year': 2022},
 {'teamName': 'Patras_Uni_Hellas', 'teamID': 4505, 'year': 2022},
 {'teamName': 'Peking', 'teamID': 4298, 'year': 2022},
 {'teamName': 'Portland', 'teamID': 4457, 'year': 2022},
 {'teamName': 'PuiChing_Macau', 'teamID': 4340, 'year': 2022},
 {'teamName': 'Qdai', 'teamID': 4206, 'year': 2022},
 {'teamName': 'Queens_Canada', 'teamID': 4347, 'year': 2022},
 {'teamName': 'RBHS_SanDiego_CA', 'teamID': 4513, 'year': 2022},
 {'teamName': 'RDFZ-CHINA', 'teamID': 4405, 'year': 2022},
 {'teamName': 'REC-CHENNAI', 'teamID': 4509, 'year': 2022},
 {'teamName': 'RS_Joint_China', 'teamID': 4401, 'year': 2022},
 {'teamName': 'RS_United_China', 'teamID': 4402, 'year': 2022},
 {'teamName': 'RUBochum', 'teamID': 4293, 'year': 2022},
 {'teamName': 'RUM-UPRM', 'teamID': 4460, 'year': 2022},
 {'teamName': 'Rochester', 'teamID': 4130, 'year': 2022},
 {'teamName': 'SCU-China', 'teamID': 4383, 'year': 2022},
 {'teamName': 'SCUT-China', 'teamID': 4263, 'year': 2022},
 {'teamName': 'SHBS-BANZ', 'teamID': 4411, 'year': 2022},
 {'teamName': 'SHSBNU_China', 'teamID': 4255, 'year': 2022},
 {'teamName': 'SHSID', 'teamID': 4280, 'year': 2022},
 {'teamName': 'SJTU-BioX-Shanghai', 'teamID': 4181, 'year': 2022},
 {'teamName': 'SJTU-software', 'teamID': 4328, 'year': 2022},
 {'teamName': 'SMS_Shenzhen', 'teamID': 4224, 'year': 2022},
 {'teamName': 'SUNY_Oneonta', 'teamID': 4268, 'year': 2022},
 {'teamName': 'SUSTech_EMB', 'teamID': 4266, 'year': 2022},
 {'teamName': 'SUSTech_Shenzhen', 'teamID': 4425, 'year': 2022},
 {'teamName': 'SUSTech_Shenzhen_HCL', 'teamID': 4470, 'year': 2022},
 {'teamName': 'SYPHU-China', 'teamID': 4230, 'year': 2022},
 {'teamName': 'SYSU-CHINA', 'teamID': 4395, 'year': 2022},
 {'teamName': 'SYSU-Software', 'teamID': 4265, 'year': 2022},
 {'teamName': 'SZ-SHD', 'teamID': 4283, 'year': 2022},
 {'teamName': 'SZPT-CHINA', 'teamID': 4325, 'year': 2022},
 {'teamName': 'SZU-China', 'teamID': 4286, 'year': 2022},
 {'teamName': 'Seoul_Korea', 'teamID': 4317, 'year': 2022},
 {'teamName': 'Sesame_Shenzhen', 'teamID': 4299, 'year': 2022},
 {'teamName': 'ShanghaiTech_China', 'teamID': 4115, 'year': 2022},
 {'teamName': 'Shanghai_HS', 'teamID': 4276, 'year': 2022},
 {'teamName': 'Shanghai_Metropolis', 'teamID': 4278, 'year': 2022},
 {'teamName': 'Shanghai_United', 'teamID': 4277, 'year': 2022},
 {'teamName': 'Shanghai_city', 'teamID': 4248, 'year': 2022},
 {'teamName': 'Sheffield', 'teamID': 4451, 'year': 2022},
 {'teamName': 'Shym_BIL_NIS', 'teamID': 4521, 'year': 2022},
 {'teamName': 'Sogang_Korea', 'teamID': 4267, 'year': 2022},
 {'teamName': 'Sorbonne_U_Paris', 'teamID': 4316, 'year': 2022},
 {'teamName': 'Stanford', 'teamID': 4466, 'year': 2022},
 {'teamName': 'Stockholm', 'teamID': 4214, 'year': 2022},
 {'teamName': 'Stony_Brook', 'teamID': 4235, 'year': 2022},
 {'teamName': 'SuZhou_Union', 'teamID': 4124, 'year': 2022},
 {'teamName': 'SubCat_China', 'teamID': 4279, 'year': 2022},
 {'teamName': 'SubCat_Shanghai', 'teamID': 4251, 'year': 2022},
 {'teamName': 'Sydney_Australia', 'teamID': 4488, 'year': 2022},
 {'teamName': 'TAMU', 'teamID': 4484, 'year': 2022},
 {'teamName': 'TAU_Israel', 'teamID': 4219, 'year': 2022},
 {'teamName': 'THINKER_CHINA', 'teamID': 4153, 'year': 2022},
 {'teamName': 'TJUSLS_China', 'teamID': 4152, 'year': 2022},
 {'teamName': 'TKS_International', 'teamID': 4520, 'year': 2022},
 {'teamName': 'TU-Eindhoven', 'teamID': 4160, 'year': 2022},
 {'teamName': 'TUDelft', 'teamID': 4361, 'year': 2022},
 {'teamName': 'TU_Braunschweig', 'teamID': 4184, 'year': 2022},
 {'teamName': 'TU_Dresden', 'teamID': 4365, 'year': 2022},
 {'teamName': 'Tec-Chihuahua', 'teamID': 4147, 'year': 2022},
 {'teamName': 'Tec-Monterrey', 'teamID': 4506, 'year': 2022},
 {'teamName': 'TecCCM', 'teamID': 4464, 'year': 2022},
 {'teamName': 'TecCEM', 'teamID': 4260, 'year': 2022},
 {'teamName': 'TecMonterrey_GDL', 'teamID': 4447, 'year': 2022},
 {'teamName': 'Technion-Israel', 'teamID': 4179, 'year': 2022},
 {'teamName': 'Thailand_RIS', 'teamID': 4314, 'year': 2022},
 {'teamName': 'TheKingsSchool_AU_HS', 'teamID': 4324, 'year': 2022},
 {'teamName': 'Thessaloniki', 'teamID': 4141, 'year': 2022},
 {'teamName': 'Thessaloniki_Meta', 'teamID': 4170, 'year': 2022},
 {'teamName': 'Thessaly', 'teamID': 4213, 'year': 2022},
 {'teamName': 'Thinker-Shenzhen', 'teamID': 4502, 'year': 2022},
 {'teamName': 'Tianjin', 'teamID': 4362, 'year': 2022},
 {'teamName': 'TokyoTech', 'teamID': 4419, 'year': 2022},
 {'teamName': 'Tongji_China', 'teamID': 4228, 'year': 2022},
 {'teamName': 'Tongji_Software', 'teamID': 4272, 'year': 2022},
 {'teamName': 'Toronto', 'teamID': 4479, 'year': 2022},
 {'teamName': 'Toulouse_INSA-UPS', 'teamID': 4197, 'year': 2022},
 {'teamName': 'Tsinghua', 'teamID': 4307, 'year': 2022},
 {'teamName': 'Tuebingen', 'teamID': 4208, 'year': 2022},
 {'teamName': 'UAM', 'teamID': 4422, 'year': 2022},
 {'teamName': 'UAlberta-Canada', 'teamID': 4443, 'year': 2022},
 {'teamName': 'UBC-Okanagan', 'teamID': 4350, 'year': 2022},
 {'teamName': 'UBC_Vancouver', 'teamID': 4296, 'year': 2022},
 {'teamName': 'UCAS-China', 'teamID': 4256, 'year': 2022},
 {'teamName': 'UCBerkeley', 'teamID': 4394, 'year': 2022},
 {'teamName': 'UCL', 'teamID': 4417, 'year': 2022},
 {'teamName': 'UCSC', 'teamID': 4190, 'year': 2022},
 {'teamName': 'UChicago', 'teamID': 4269, 'year': 2022},
 {'teamName': 'UConn', 'teamID': 4465, 'year': 2022},
 {'teamName': 'UCopenhagen', 'teamID': 4247, 'year': 2022},
 {'teamName': 'UESTC-BioTech', 'teamID': 4335, 'year': 2022},
 {'teamName': 'UFMG_UFV_Brazil', 'teamID': 4349, 'year': 2022},
 {'teamName': 'UFlorida', 'teamID': 4412, 'year': 2022},
 {'teamName': 'UGA_Grenoble', 'teamID': 4337, 'year': 2022},
 {'teamName': 'UIUC_Illinois', 'teamID': 4436, 'year': 2022},
 {'teamName': 'UIncheon', 'teamID': 4310, 'year': 2022},
 {'teamName': 'ULaval', 'teamID': 4346, 'year': 2022},
 {'teamName': 'UMA_MALAGA', 'teamID': 4368, 'year': 2022},
 {'teamName': 'UM_Macau', 'teamID': 4357, 'year': 2022},
 {'teamName': 'UManitoba', 'teamID': 4323, 'year': 2022},
 {'teamName': 'UMaryland', 'teamID': 4483, 'year': 2022},
 {'teamName': 'UNILausanne', 'teamID': 4209, 'year': 2022},
 {'teamName': 'UNSW_Australia', 'teamID': 4467, 'year': 2022},
 {'teamName': 'UOregon', 'teamID': 4215, 'year': 2022},
 {'teamName': 'UPNAvarra_Spain', 'teamID': 4453, 'year': 2022},
 {'teamName': 'UPenn', 'teamID': 4444, 'year': 2022},
 {'teamName': 'USAFA', 'teamID': 4132, 'year': 2022},
 {'teamName': 'USC_Dornsife', 'teamID': 4381, 'year': 2022},
 {'teamName': 'USP-EEL-Brazil', 'teamID': 4496, 'year': 2022},
 {'teamName': 'USTC', 'teamID': 4231, 'year': 2022},
 {'teamName': 'USTC-Software', 'teamID': 4240, 'year': 2022},
 {'teamName': 'UTokyo', 'teamID': 4238, 'year': 2022},
 {'teamName': 'UZurich', 'teamID': 4387, 'year': 2022},
 {'teamName': 'UiOslo_Norway', 'teamID': 4450, 'year': 2022},
 {'teamName': 'Uni-Hamburg', 'teamID': 4472, 'year': 2022},
 {'teamName': 'Unicamp_Brazil', 'teamID': 4435, 'year': 2022},
 {'teamName': 'UniofBath', 'teamID': 4418, 'year': 2022},
 {'teamName': 'Uppsala', 'teamID': 4378, 'year': 2022},
 {'teamName': 'VIT_Vellore', 'teamID': 4372, 'year': 2022},
 {'teamName': 'Vilnius-Lithuania', 'teamID': 4380, 'year': 2022},
 {'teamName': 'Virginia', 'teamID': 4477, 'year': 2022},
 {'teamName': 'WHU-China', 'teamID': 4144, 'year': 2022},
 {'teamName': 'WLC-Milwaukee', 'teamID': 4366, 'year': 2022},
 {'teamName': 'WVHS_SanDiego', 'teamID': 4191, 'year': 2022},
 {'teamName': 'WWU_Muenster', 'teamID': 4188, 'year': 2022},

In [ ]:
# Save the 2022 roster data to a tsv file
# API call to get the team roster for 2022 (because the team roster tsv file that we have now is anonymized)
# Reusing some code from get_team_rosters-checkpoint.ipynb 

skipped_entries = []

def get_roster(team):
    year = team.get("year")
    team_id = team.get("teamID")
    team_name = team.get("teamName")
    url = f"https://api.igem.org/v1/teams/{team_id}/roster"

    try:
        r = requests.get(url)
        r.raise_for_status()
        data = r.json()
        records = []

        role_map = {
            "student": "Student Member",
            "student-leader": "Student Leader",
            "instructor": "Instructor",
            "primary-pi": "Primary PI",
            "secondary-pi": "Secondary PI"
        }

        for entry in data:
            roster_uuid = entry.get("uuid", "")
            role_key = entry.get("role", "").lower()
            role = role_map.get(role_key, role_key.replace("-", " ").title())

            member = entry.get("member") or {}
            user = member.get("user") or {}

            records.append({
                "FullName": user.get("publicName", ""),
                "TeamID": team_id,
                "Team": team_name,
                "Year": year,
                "Role": role,
                "Username": member.get("username", ""),
                "RosterUUID": roster_uuid,
                "UserUUID": member.get("uuid", ""),
                "UserID": user.get("id", ""),    
            })

        return records

    except Exception as e:
        print(f"Error for team {team_name} ({team_id}): {e}")
        skipped_entries.append({
            "Year": year,
            "TeamID": team_id,
            "Team": team_name,
            "Error": str(e),
            "RawEntry": None
        })
        return []


# Execution
all_2022_records = []
for team in tqdm(teams_names_ids_2022, desc="Fetching rosters"):
    all_2022_records.extend(get_roster(team))

df_roster = pd.DataFrame(all_2022_records)
df_roster.sort_values(["Team", "Role"], inplace=True)
df_roster.to_csv("../data/attributions/2022_attributions/team_rosters_2022.tsv", sep="\t", index=False)
print(f"Saved team_rosters_2022.tsv with {len(df_roster)} rows")

Fetching rosters: 100%|██████████| 360/360 [00:23<00:00, 15.36it/s]

Saved team_rosters_2022.tsv with 7762 rows

In [26]:
df_roster = pd.read_table("../data/attributions/2022_attributions/team_rosters_2022.tsv")

In [ ]:
# Save Teams and FullNames in a dictionary (later used for LLM prompts)
roster_2022_dict = (
    df_roster
    .groupby("Team")["FullName"]
    .apply(list)
    .to_dict()
)

roster_2022_dict

In [ ]:
# Save the dictionary as a JSON file

roster_output_path = "../data/attributions/2022_attributions/team_rosters_2022.json"

with open(roster_output_path, "w", encoding="utf-8") as f:
    json.dump(roster_2022_dict, f, ensure_ascii=False, indent=2)