# Manual Annotation of Team Attributions for LLM Validation Purposes

In the first part of this notebook, 14 surveyed teams are randomly selected to have their members and task descriptions manually extracted. The manual annotation of members and tasks is done in order to create a dataframe with columns `"RawTextName"`, `"RosterName"`, `"Team"`, and `"TasksDescription"`. This dataframe is then turned into a JSON file, and will be used as a gold standard in order to evaluate the performance of the LLM doing the same name and task extraction from raw attributions texts.

In the second part, 5 out of 6 surveyed teams without extracted raw attributions texts (check `6_match_teams_2022_attributions`) are also manually annotated. Examples from these teams are used for defining the few-shot prompt and the rules for the LLM. During the prompt engineering process, these teams are used as validation that the LLMs perform well.

## 1. Random Surveyed Teams Selection for Model Evaluation

In [1]:
import pandas as pd
import random
import json
import re
import math

In [2]:
df_survey = pd.read_csv("../data/igem_ties_surveys/2022/survey_tasks.csv")

In [5]:
df_survey['user_id'].nunique()

776

In [5]:
df_team_meta = pd.read_table("../data/igem_scrapping_2025/team_meta_full.tsv")

In [12]:
# Surveyed teams without attributions

teams_without_attributions = ['ITESO_Guadalajara', 'HKU_HongKong', 'Patras_Medicine', 'NJU-China', 'Stanford', 'Vilnius-Lithuania' ]

In [13]:
# Randomly select 14 unique teams from the survey data

random.seed(42)  
filtered_teams = [team for team in df_survey["team"].dropna().unique() if team not in teams_without_attributions]
random_teams = random.sample(filtered_teams, min(14, len(filtered_teams)))

In [14]:
random_teams

['Technion-Israel',
 'CSMU_Taiwan',
 'Aalto-Helsinki',
 'UPNAvarra_Spain',
 'ICT-Mumbai',
 'Goettingen',
 'Freiburg',
 'Cambridge',
 'CPU_Nanjing',
 'UCBerkeley',
 'Sogang_Korea',
 'BostonU_HW',
 'TU_Braunschweig',
 'Montpellier']

I forgot to add a condition for only accepted teams. As UCBerkeley was withdrawn, it was not used in the manual annotation. Therefore, we will randomly select one more surveyed team so we could have 14 teams for model evaluation.

In [10]:
# Randomly select 1 more team from the survey data

random.seed(43)

accepted_teams = df_team_meta[df_team_meta["Status"] == "accepted"]["Team"].unique()

filtered_accepted_teams = [
    team for team in df_survey["team"].dropna().unique()
    if team in accepted_teams and team not in teams_without_attributions
]

random_accepted_team = random.sample(filtered_accepted_teams, min(1, len(filtered_accepted_teams)))

In [11]:
random_accepted_team

['Aboa']

In [15]:
random_teams.append(random_accepted_team[0])

In [16]:
random_teams

['Technion-Israel',
 'CSMU_Taiwan',
 'Aalto-Helsinki',
 'UPNAvarra_Spain',
 'ICT-Mumbai',
 'Goettingen',
 'Freiburg',
 'Cambridge',
 'CPU_Nanjing',
 'UCBerkeley',
 'Sogang_Korea',
 'BostonU_HW',
 'TU_Braunschweig',
 'Montpellier',
 'Aboa']

## 2. Member Names and Raw Task Descriptions

### 2.1 Test Teams

In [17]:
def load_attributions_json(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data

filepath = "../data/attributions/2022_attributions/raw_attributions_2022.json"

data = load_attributions_json(filepath)

In [18]:
random_teams_attributions_dict = [entry for entry in data if entry["teamName"] in random_teams]

In [19]:
# Save the random teams' raw attributions to a new JSON file
output_path = "../data/attributions/2022_attributions/random_teams_raw_attributions_2022.json"

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(random_teams_attributions_dict, f, ensure_ascii=False, indent=2)

In [20]:
df_roster = pd.read_table("../data/attributions/2022_attributions/team_rosters_2022.tsv")

In [ ]:
# Randomly selected teams' rosters

roster_random_teams_dict = (
    df_roster[df_roster["Team"].isin(random_teams)]
    .groupby("Team")["FullName"]
    .apply(list)
    .to_dict()
)

In [22]:
roster_random_teams_dict

{'Aalto-Helsinki': ['Ilse Kaaja',
  'Juuso Taskinen',
  'Rishi Banerjee',
  'Sami Jalil',
  'A. Sesilja Aranko',
  'Ville Paavilainen',
  'Heli Viskari',
  'Markus Linder',
  'Melissa Hendr�n',
  'Veera Kurki',
  'Amna Gul',
  'Anniina Könönen',
  'Diogo Dias',
  'Hanna Nebelung',
  'Joose Lankia',
  'Lilith Heiland',
  'Mari Keskiivari',
  'Zsofia Hesketh'],
 'Aboa': ['Pauli Kallio',
  'Juuli Hietarinne',
  'Malin Eriksson',
  'Anni Marjomaa',
  'Evelina Ojaniittu',
  'Iida Raaska',
  'Jesper Mickos',
  'Jonna Pohjankukka',
  'Kevät Sova',
  'Kristiina Keski-Oja',
  'Minttu Turunen',
  'Nelli Heiskanen',
  'Otto Rydman',
  'Sini Kylä-Kaila',
  'Sofia Antin'],
 'BostonU_HW': ['Diana Arguijo',
  'Hailey Lenn Gordon',
  'Douglas Densmore',
  'Alexander Barutis',
  'Aya Kassem',
  'Julia Nowak',
  'Stephen Sweet',
  'zakir kadwa'],
 'CPU_Nanjing': ['Jingzhi Hu',
  'Hai Qian',
  'Xin Wang',
  'Mayu Shan',
  'Chang Liu',
  'Chengjun Yuan',
  'Haotian Liu',
  'Qiuhan Ren',
  'Ruochen Qian',
  'Shaohang Zhang',
  'Siyi Fei',
  'Siyuan Chen',
  'Tianchang Xia',
  'Xiaohui Ma',
  'Xinyi Xia',
  'Ye Gu',
  'Zexuan Wei',
  'Zeyu Cai',
  'Zijin Pu'],
 'CSMU_Taiwan': ['DE-MING, CHEN',
  'JUAN LIANG-HSUEH',
  'Kuan Hung Chen',
  'Lee Wei Ling',
  'Liu, Peng-Shin',
  'SHIH CHIA HSIEN',
  'SUE,XIN-YUAN',
  'Chang Wen-Wei',
  'Ming-Shiou Jan',
  'LIU YU-FAN',
  'TSAI, JIUN-JEN',
  'YU-TING, CHOU',
  'CHAO-CHING, LIU',
  'CHENG-HAO, LAI',
  'CHIEN-YU, LIN',
  'CHU-YI, HSUEH',
  'EDWARD CHIANG',
  'HSU-YEN KAO',
  'KAO, CHIEH-HSIN',
  'TING-HUNG, CHOU',
  'TZU-LIN LIU',
  'WEI-AN, HUANG',
  'WEI-CHENG, HSIAO',
  'WEN-HUI, SU',
  'WU, SHU-YI',
  'YU-CI, CHANG',
  'YUN-PEI, TSAI',
  'ZONG-HAN LIN'],
 'Cambridge': ['Alberto Echevarr�a-Poza',
  'Anamay Shetty',
  'Camillo Moschner',
  'Charlie Wedd',
  'Chris N Micklem',
  'Emma Jones',
  'Georgeos Hardo',
  'Ignacy Bonter',
  'Jarrod Shilts',
  'Kavi H Shah',
  'Sean Thompson',
  'Stephanie Avraamides',
  'Somenath Bakshi',
  'Jenny Molloy',
  'Anh Phuoc Nguyen Phung',
  'Charles Anderton',
  'Joni Wildman',
  'Kazimir Uzwyshyn Jones',
  "Shau'ri Wiggins",
  'Yuen Shan Ho'],
 'Freiburg': ['Paulina Sofie Kaas',
  'Barbara Di Ventura',
  'Nicole Gensch',
  'Pavel Salavei',
  'Andreas Riedlberger',
  'Anne Smedegaard',
  'Fabian Stockert',
  'Jeremy Ranniger',
  'Johanna Gerstenecker',
  'Jonas Widder',
  'Leon-Samuel Icking',
  'Michael Spadt',
  'Nikita Edel',
  'Pia Gescher',
  'Selene Franchini'],
 'Goettingen': ['Rolf Daniel',
  'Alexander Rosenberger',
  'Bjoern Hormes',
  'Jasmin Petrovac',
  'Julia Fricke',
  'Katharina Stark',
  'Lea Hahn',
  'Lea Trost',
  'S�nke Beewen'],
 'ICT-Mumbai': ['Prajwal Purushottam Dongare',
  'Gurpreet Kaur Bharj',
  'Harikrishnan R Namboothiri',
  'Mihir Dakappagari',
  'Ruchira Iyer',
  'Swarali Paranjape',
  'Vaibhav Vishwanath',
  'Shamlan Reshamwala',
  'Darsh Vithlani',
  'Hrishabh Singh',
  'Aarya Darak',
  'Anirudh Venkataraman Veliyur',
  'Arya Ajit Gohad',
  'Deepro Bandyopadhyay',
  'Ishwari Joshi',
  'Jaysen Shah',
  'Karanveer Singh Khurana',
  'Kaustubh Raju Wadekar',
  'Peehu Joshi',
  'Ritesh Reddy Seri',
  'Sahil Jadhav',
  'Shauryaraj Jilkar',
  'Stuti Mishra',
  'Taha Umrethwala',
  'Vijayank Raj Chouhan'],
 'Montpellier': ['Jerome Bonnet',
  'Christine Doucet',
  'Diego Cattoni',
  'Guillaume Cambray',
  'Luca Ciandrini',
  'Ali Kanso',
  'Christelle AlJamous',
  'Emilie Costes',
  'Hye Rin An',
  'Nessim Louafi'],
 'Sogang_Korea': ['SeungYeon LEE',
  'Agustina Setiawati',
  'Albertus Ivan Brilian',
  'Monica Cahyaning Ratri',
  'Bakti Saputra',
  'Kwanwoo Shin',
  'Seokhwan Jeong',
  'Amelia Husin',
  'injun Lee',
  'Jungmin Hamm',
  'Andreas Felix Tan',
  'Flavia Setyajati',
  'JaeJin Lee',
  'Jiae Park',
  'Jiwon Kang',
  'Kang JiSeok',
  'LEE YOONGEUN',
  'SeongHyeon Lim',
  'Seoyeong Lee',
  'Vincentia Prasetyo',
  'Youngjun Jo'],
 'TU_Braunschweig': ['Boas Pucker',
  'Benjamin Harder',
  'Dorothee Börstling',
  'Fabienne Spang',
  'Frauke Drobek',
  'Melina Nowak',
  'Samuel Nestor Meckoni',
  'Simon Klute ',
  'Sina Huxhagen'],
 'Technion-Israel': ['Naor Granik',
  'Or Willinger',
  'Shira Levi',
  'Roee Amit',
  'Nisrine Lahoud',
  'Maia Lehrman',
  'Amit Nelkin',
  'Baraah Rashed',
  'Irina Shkalikov',
  'Iser Snoyman',
  'Matan Hoory',
  'Mazal Faraj',
  'Nova Noiman',
  'Ran Benayoun',
  'Reut Laufer',
  'Yana Shklovski',
  'Yasmin Habib'],
 'UCBerkeley': ['Chris Anderson',
  'Cassandra Areff',
  'Elena Mujica',
  'Heyuan "Michael" Ni',
  'Mrunali Manjrekar',
  'Adam Kazerounian',
  'Albert Qiang',
  'Alvie Kam',
  'Amad Jalil',
  'Angelica Lam',
  'Anya Raju',
  'Arshia Deep',
  'Arthi Vaidyanathan',
  'Arvind Swamynathan',
  'Ayati Sharma',
  'Bailey Daymo',
  'Edward Pandji',
  'Ella Ramamurthy',
  'Fenmiao Zhong',
  'Gabriela Castellanos',
  'Gean Hu',
  'George Balazs',
  'George Rickus',
  'Guru Rajesh',
  'HyoJung Heo',
  'Irene Chang',
  'Isabella Murray',
  'Jacob Rulison',
  'Jacob Spiegel',
  'Jiangyu Guo',
  'John Pantigoso',
  'Kaitlyn Wang',
  'Katie Fang',
  'Katie Sie',
  'Kenneth Bryan Hsu',
  'Khushi Kethana',
  'Lukas Koller',
  'Maria Isabella Solorzano',
  'Meera Kashyap',
  'Melissa Zhou',
  'Mingya Wang',
  'Nicholas Scola',
  'Nicole Klein',
  'Nikhit Kambdur',
  'Patporn Taedullayasatit',
  'PeiWen Xiao',
  'Phil Yuantai Xie',
  'Pritika Acharya',
  'Rachelle Smith',
  'Rohan Rattan',
  'Ryan Idnani',
  'Samhita Nittala',
  'Shing Gao',
  'Shreya Ramesh',
  'Sinead de Cleir',
  'Srivibha Yellamraju',
  'Tara Pande',
  'Timothy Tu',
  'Ying-Li Su'],
 'UPNAvarra_Spain': ['Esther M GONZALEZ',
  'In�s Echeverr�a Go�i',
  'Juanjo Rubio',
  'Laura Gim�nez',
  '�lex Pascual Cid',
  'Mar�a Anc�n',
  'MAR�A-JOS� SAIZ-ABAJO',
  'Pablo Allo Martinez',
  'Rosa Murillo',
  'Ainhoa Zulet',
  'Hugo Salas Pedroarena',
  'Estibaliz Larrainzar',
  'Idoia Ariz',
  'Raquel Iriarte',
  'Sergio Mara�a Tolosa',
  'Adriana Martinez',
  'Aitor Ayape',
  'Aroa Roncal',
  'Irene Gil Lobo',
  'Javier Zabalegui Bayona',
  'Juliana Cuervo',
  'Maria Roldan Vergarachea',
  'MARIO SANTAF� M�NDEZ',
  'Marta Lopez Marsa',
  'Mikel Garcia',
  'Susana San Ildefonso Garc�a',
  'Unai Gurbindo Gonzalez']}

In the manually annotated dataset (made in Google Sheets), the `"RawTextName"` represents every member name that is found in the team's raw attributions text, but also exists in the official team's roster (external and other contributors are not considered here). The names from the attributions and the roster sometimes differ in spelling. The `"RosterName"` columns contains all names found in the team's roster. If a variant of the roster name is not found in the team's attribution text, values in columns `"RawTextName"` and `"TasksDescriptions"` are left null. Fourteen randomly selected teams are considered, with their names in the `"Team"` column. `"TasksDescription"` includes full text describing tasks of one person. The value for the `"TasksDescription"` column can be the actual tasks description and/or the team-defined task categories, whatever the team has written for each member's name. Newlines "\n" and extra blank spaces will later be removed from the descriptions. `"Comments"` column describes edge cases found in each team  (e.g., some teams include sentences that apply to all members; these sentences should be added to each individual member even if their name is not explicitly mentioned).

In [ ]:
# Load manually annotated tsv attributions

df_manual_random_attributions = pd.read_csv("../data/attributions/2022_attributions/manual_annotation/14_random_teams_tasks.tsv", sep="\t")

In [4]:
df_manual_random_attributions

,RawTextName,RosterName,Team,TasksDescription,Comments
0,Melissa Hendrén,Melissa Hendr�n,Aalto-Helsinki,is one of the team co-leads to the Aalto-Helsi...,The team does not include a name subtitle for ...
1,Veera Kurki,Veera Kurki,Aalto-Helsinki,is one of the team co-leads to the Aalto-Helsi...,NaN
2,Diogo Dias,Diogo Dias,Aalto-Helsinki,is head of the dry-lab. He is involved in the ...,NaN
3,Amna Gul,Amna Gul,Aalto-Helsinki,is an active member of the wet-lab team. She c...,NaN
4,Lilith Heiland,Lilith Heiland,Aalto-Helsinki,is head of the writing team and part of the we...,NaN
...,...,...,...,...,...
236,Minttu Turunen,Minttu Turunen,Aboa,All team members participated in the general a...,NaN
237,Nelli Heiskanen,Nelli Heiskanen,Aboa,All team members participated in the general a...,NaN
238,Otto Rydman,Otto Rydman,Aboa,All team members participated in the general a...,NaN
239,Sini Kylä-Kaila,Sini Kylä-Kaila,Aboa,All team members participated in the general a...,NaN
240,Sofia Antin,Sofia Antin,Aboa,All team members participated in the general a...,NaN

In [ ]:
# Convert to JSON format, to be comparable with model outputs
# List of objects where each object has a team name as a key, and the value is a list of members with their names and task descriptions

def convert_df_to_json_format(df):
    if 'Comments' in df.columns:
        df = df.drop(columns=['Comments'])

    json_data = []
    for team, group in df.groupby('Team'):
        members = group[['RosterName', 'RawTextName', 'TasksDescription']].to_dict(orient='records')
        json_data.append({team: members})

    return json_data

In [5]:
json_test_data = convert_df_to_json_format(df_manual_random_attributions)
json_test_data

[{'Aalto-Helsinki': [{'RosterName': 'Melissa Hendr�n',
    'RawTextName': 'Melissa Hendrén',
    'TasksDescription': 'is one of the team co-leads to the Aalto-Helsinki team. She is head of the wet-lab team and involved in fundraising, collaborations with other teams, writing, synbio and travelling organisation.'},
   {'RosterName': 'Veera Kurki',
    'RawTextName': 'Veera Kurki',
    'TasksDescription': 'is one of the team co-leads to the Aalto-Helsinki team. She is head of the human practices, the social media team and chair of synbio. She is part of the wet-lab and involved in fundraising, collaborations, writing, social media and travelling organisation.'},
   {'RosterName': 'Diogo Dias',
    'RawTextName': 'Diogo Dias',
    'TasksDescription': 'is head of the dry-lab. He is involved in the data analysis of the project, blogpost writing and review as well as participating in the development of the promotion video.'},
   {'RosterName': 'Amna Gul',
    'RawTextName': 'Amna Gul',
    'TasksDescription': 'is an active member of the wet-lab team. She contributes to the project in several ways, including through fundraising, collaborations, human practices, writing, and the production of a promotional video.'},
   {'RosterName': 'Lilith Heiland',
    'RawTextName': 'Lilith Heiland',
    'TasksDescription': 'is head of the writing team and part of the wet-lab team. She is involved in fundraising, collaborations, human practices, promotion video, and travel organisation.'},
   {'RosterName': 'Zsofia Hesketh',
    'RawTextName': 'Zsófia Hesketh',
    'TasksDescription': 'is head of the collaboration team and part of the wet-lab team. She is involved in writing, human practices, and travel planning.'},
   {'RosterName': 'Mari Keskiivari',
    'RawTextName': 'Mari Keskiivari',
    'TasksDescription': 'is head of the graphic design team and part of the wet-lab team. She is involved in writing, human practices, promotion video, social media, synbio, and travel organisation.'},
   {'RosterName': 'Anniina Könönen',
    'RawTextName': 'Anniina Könönen',
    'TasksDescription': 'is head of the fundraising team and part of the dry-lab team. She is involved in collaborations, writing, synbio and travel planning.'},
   {'RosterName': 'Joose Lankia',
    'RawTextName': 'Joose Lankia',
    'TasksDescription': 'is head of the promotion video team and part of the dry-lab team. He is involved in collaborations, programming, writing, human practices, graphic design, and the social media team.'},
   {'RosterName': 'Hanna Nebelung',
    'RawTextName': 'Hanna Nebelung',
    'TasksDescription': 'is head of the programming team and part of the dry-lab team. She is involved in collaborations, and human practices teams.'},
   {'RosterName': 'Heli Viskari',
    'RawTextName': 'Heli Viskari',
    'TasksDescription': "Heli is one of the principal investigators of the Aalto-Helsinki 2022 iGEM team. Her help has been crucial throughout our iGEM journey, by being present throughout the ideation phase and giving us feedback of how to progress. Additionally, the laboratory space at Aalto University was provided by Heli, and Heli has helped us actively with orders throughout the summer - even contributing some of her own teaching budget to the iGEM team. Furthermore, she gave us instructions on some simple lab tasks to ensure biosafety measures are in place in our group's work. Thank you very much Heli for all the dedicated work that you have provided to our iGEM team!"},
   {'RosterName': 'Markus Linder',
    'RawTextName': 'Markus Linder',
    'TasksDescription': 'Markus is one of the principal investigators of the Aalto-Helsinki 2022 iGEM team. He guided us through the brainstorming process and gave feedback to our initial ideas encouraging us to consider the combination of our potential earlier ideas. Furthermore, he approved together with Heli the additional financial support from the teaching budget to our iGEM team. We are very grateful for the help and guidance we received from you, Markus..'},
   {'RosterName': 'A. Sesilja Aranko',
    'RawTextName': 'Sesilja Aranko',
    'TasksDescription': 'Sesilja is one of the advisors of the Aalto-Helsinki iGEM 2022 team. She has helped the team in the initial ideation phase giving us advice, but was also essential during the realisation of the project in the lab. Sesilja provided help during the construction of the bioreporter and also in the initial stage of the DARPin library and was essential for providing us with information of the presence both location wise and stock wise of lab equipment and chemicals. Additionally, the team thanks you, Sesilja, for helping us develop a schedule for our lab work.'},
   {'RosterName': 'Ville Paavilainen',
    'RawTextName': 'Ville Paavilainen',
    'TasksDescription': 'Ville is one of the advisors of the Aalto-Helsinki 2022 iGEM team. His guidance was crucial throughout our ideation and brainstorming phase. We received valuable input from him throughout the ideation phase and also in setting up our lab protocols. Ville connected us to key contacts including Anja Paatero and Kah Ying Ng for checking our protocols for ribosome display. Additionally, he provided us lab space to work in to test our initial protocols. Ville, we thank you for your independable help in setting up the ribosome display.'},
   {'RosterName': 'Ilse Kaaja',
    'RawTextName': 'Ilse Kaaja',
    'TasksDescription': 'Ilse is one of the PhD mentors of the Aalto-Helsinki iGEM team. She has been very helpful during the beginning of the project, as she also has been a part of the Aalto-Helsinki iGEM team in 2019. We have got help with iGEM registry questions, and common questions we have had during our meetings with the mentors. We are very grateful for the support Ilse has given us during the project.'},
   {'RosterName': 'Juuso Taskinen',
    'RawTextName': 'Juuso Taskinen',
    'TasksDescription': 'Juuso is one of the PhD mentors of the Aalto-Helsinki iGEM team. He was essential in guiding us throughout our project by providing questions that made us think deeper and in more detail about our approaches. Additionally, Juuso was present to help with wet-lab questions that were too complicated for us to solve. We thank you very much for the impact you had on our project.'},
   {'RosterName': 'Sami Jalil',
    'RawTextName': 'Sami Jalil',
    'TasksDescription': 'Sami is one of the Phd mentors of the Aalto-Helsinki iGEM team. His help has been essential for the set up of our bioreporter. He reviewed with us the bioreporter and the integration of it into our plasmid. Furthermore, he provided us with the essential plasmid pET42b-HF-BE3 required for the expression of our GFP-DARPin, so that we could pass it to the Dresden iGEM team. We thank you, Sami, for the constant support that you showed our team.'},
   {'RosterName': 'Rishi Banerjee',
    'RawTextName': 'Rishi Banerjee',
    'TasksDescription': 'Rishi is one of the Phd mentors of the Aalto-Helsinki team. He was helpful in the beginning of the project for primer design. He provided online resources for primer design and annealing temperature calculations.'}]},
 {'Aboa': [{'RosterName': 'Pauli Kallio',
    'RawTextName': 'Pauli Kallio',
    'TasksDescription': "\\nOur primary PI Pauli Kallio provided us with useful insight throughout our brainstorming process, which helped us direct our project's focus on detection systems. He also helped us with troubleshooting as well as supported us throughout the iGEM year."},
   {'RosterName': 'Juuli Hietarinne',
    'RawTextName': 'Juuli Hietarinne',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. \\nJuuli continued her last year’s iGEM journey as a team leader with Malin. They shared various organizational and guiding tasks, trying to teach as much as possible to new iGEMers and to ensure that all relevant criteria were met. In addition to her role as a team leader, she was also the head of Media. Juuli’s media-related tasks included, in addition to the organizational duties, creating social media content, writing a piece of news, and updating our own website. Besides, she actively participated in wiki coding and layout planning, fundraising activities, and promotion video planning. Juuli’s human practices -related responsibilities included for example planning and creating educational posts published on our social media accounts, creating other educational material for school visits, and taking part in some collaborations.'},
   {'RosterName': 'Malin Eriksson',
    'RawTextName': 'Malin Eriksson',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing.\\nMalin continued her role as a team leader from last year and shared the task with Juuli. Together with Juuli she tried her best to share everything she had learnt from her iGEM 2021 experience to the new team to avoid repeating past mistakes and set the team up for success. This included, for example, organizational tasks and scheduling. Additionally, Malin helped the wet lab subteam get started, negotiated to get a laboratory for the team to work in, provided everyday support and advice to the lab team in the beginning of the summer, and actively led many collaboration and partnership meetings. She also had smaller roles within the team’s human practices and fundraising work, which included contributions to educational materials, interviews with stakeholders, and securing financial assistance from the university.'},
   {'RosterName': 'Anni Marjomaa',
    'RawTextName': 'Anni Marjomaa',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. \\nAnni was an active member in the wet lab subteam. In addition, she contributed to the educational materials for school visits as well as to educational posts published on our social media accounts. Anni was also arranging some of our integrated human practices meetings with farmers as well as participated in Heureka workshops, school visits, and the Study in Turku fair where we spread knowledge about iGEM and synthetic biology in general.'},
   {'RosterName': 'Evelina Ojaniittu',
    'RawTextName': 'Evelina Ojaniittu',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. \\nEvelina spent a whole summer in the lab doing our experiments. In addition, she contributed to educational posts published on social media and took care of our Facebook account in general. Evelina also participated in school visits, Heureka workshops, and the Study in Turku fair.'},
   {'RosterName': 'Iida Raaska',
    'RawTextName': 'Iida Raaska',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. \\nOur head of IT, Iida, was in charge of the coding of our wiki and she also took part in the creation of our own website. In addition to these responsibilities, Iida also contributed to dry lab work.'},
   {'RosterName': 'Jesper Mickos',
    'RawTextName': 'Jesper Mickos',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. \\nJesper, our head of Wet Lab, planned the majority of our experiments and organized our lab work. He participated in both wet lab and dry lab -related collaborations and partnerships and troubleshooting actively. In addition to the wet lab, Jesper also contributed to fundraising and human practices activities, such as the Study in Turku fair and the Science Basement talk.'},
   {'RosterName': 'Jonna Pohjankukka',
    'RawTextName': 'Jonna Pohjankukka',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. \\nJonna actively participated in fundraising, wet lab, and human practices activities. She created some social media content for Instagram and was in charge of our LinkedIn account. Jonna also contributed to the educational content for school visits and visited one school. In addition to this, she participated in the Heureka workshops for kids and in the Study in Turku fair, where we told other students about our project and iGEM. Jonna was involved in many of our collaborations and partnerships and you can also hear her voice in our promotion video.'},
   {'RosterName': 'Kevät Sova',
    'RawTextName': 'Kevät Sova',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. \\nKevät was the head of Human Practices. Alongside their responsibility as a subteam leader, they participated actively in the wet lab subteam by working in the summer. Additionally, they used their artistic creativity to participate in the Synbio-themed art journal made by the iGEM team ASU. They also arranged school visits, interviewed various researchers and farmers, and participated in the Study in Turku fair.'},
   {'RosterName': 'Kristiina Keski-Oja',
    'RawTextName': 'Kristiina Keski-Oja',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. \\nKristiina was the treasurer of the Aboa Turku ry, the organization behind our team. Thus, all money-related things were her responsibility. She was also an active member of the wet lab subteam, as well as participated in human practices and fundraising activities.'},
   {'RosterName': 'Minttu Turunen',
    'RawTextName': 'Minttu Turunen',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. \\nMinttu was our head of Visual Design, and her main responsibility was the planning, filming, and editing of our amazing promotion video. In addition, she took multiple photos for our wiki, participated in the planning of our wiki layout, and contributed to educational posts published on our social media accounts.'},
   {'RosterName': 'Nelli Heiskanen',
    'RawTextName': 'Nelli Heiskanen',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. \\nNelli was our head of Fundraising. Her duties as a subteam leader consisted of planning the strategies for fundraising, such as contacting possible sponsors, creating value for the sponsors, creating presentation materials, and organizing meetings. Alongside her responsibility as a subteam leader, she created social media content as well as educational material for our school visits. She also contributed to the promotion video planning and acting, as well as participated in some other activities, such as the Science Basement talk.'},
   {'RosterName': 'Otto Rydman',
    'RawTextName': 'Otto Rydman',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. \\nOtto was a wet lab subteam member and also participated in multiple human practices activities, including stakeholder interviews. Furthermore, he contributed to the planning of our promotion video and was the main film star in it.'},
   {'RosterName': 'Sini Kylä-Kaila',
    'RawTextName': 'Sini Kylä-Kaila',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. \\nSini was the chairperson of Aboa Turku ry, the organization behind our team. She also contributed to fundraising, visual design, and media activities in the spring.'},
   {'RosterName': 'Sofia Antin',
    'RawTextName': 'Sofia Antin',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. \\nSofia participated in the wet lab work.'}]},
 {'BostonU_HW': [{'RosterName': 'Diana Arguijo',
    'RawTextName': 'Diana Arguijo',
    'TasksDescription': '\\nMicrofluidic Device Design\\nMicrofluidic Device Diagnostics\\nTechnical Support\\nLab Maintenance'},
   {'RosterName': 'Hailey Lenn Gordon',
    'RawTextName': 'Hailey Lenn Gordon ',
    'TasksDescription': '\\nOutreach Coordinator\\nSocial Events Coordinator\\nTechnical Support\\nFundraising\\nHuman Practices Coordinator'},
   {'RosterName': 'Douglas Densmore',
    'RawTextName': 'Douglas Densmore',
    'TasksDescription': '\\nTeam Coordinator\\nTechnical Support'},
   {'RosterName': 'Alexander Barutis',
    'RawTextName': 'Alex Barutis',
    'TasksDescription': '\\nBackground Research\\nIncubator Design\\nCommercial\\nWeb App Development\\nModeling\\nDocumentation\\nWiki'},
   {'RosterName': 'Aya Kassem',
    'RawTextName': 'Aya Kassem',
    'TasksDescription': '\\nBackground Research\\nPressure System\\nIncubator\\nWeb App Development\\nSystem Automation\\nMicrofluidic Fabrication\\nElectronic Managment'},
   {'RosterName': 'Julia Nowak',
    'RawTextName': 'Julia Nowak',
    'TasksDescription': '\\nBackground Research\\nAquatic Environment\\nCommercial\\nDocumentation\\nMicrofluidic Fabrication\\nDocumentation\\nSafety'},
   {'RosterName': 'Stephen Sweet',
    'RawTextName': 'Stephen Sweet',
    'TasksDescription': '\\nBackground Research\\nSampling System\\nPressure System\\nDocumentation\\nElectronic Management\\nHousing'},
   {'RosterName': 'zakir kadwa',
    'RawTextName': 'Zakir Kadwa',
    'TasksDescription': '\\nBackground Research\\nAquatic Environment\\nHousing\\nModeling\\nDocumentation'}]},
 {'CPU_Nanjing': [{'RosterName': 'Jingzhi Hu',
    'RawTextName': 'Jingzhi Hu',
    'TasksDescription': 'In the initial design and later practice of our project, both Dr. Xin Wang and Dr. Jingzhi Hu gave us many constructive suggestions, which made our project go smoothly. '},
   {'RosterName': 'Hai Qian',
    'RawTextName': 'Hai Qian',
    'TasksDescription': 'Without his help, we cannot complete our project. '},
   {'RosterName': 'Xin Wang',
    'RawTextName': 'Xin Wang',
    'TasksDescription': 'In the initial design and later practice of our project, both Dr. Xin Wang and Dr. Jingzhi Hu gave us many constructive suggestions, which made our project go smoothly. '},
   {'RosterName': 'Mayu Shan',
    'RawTextName': 'Mayu Shan',
    'TasksDescription': 'Student Leader\\nAs the leader of CPU_Nanjing, he is responsible for the overall management of team affairs and the coordination of different departments. He is involved in HP design and organizes field visits, hardware construction and education activities. participated in the construction of the hardware to verify the feasibility of manufacturing phosphate from materials available on terrestrial planets. was in charge of organizing field visits and producing online education materials together with Tianchang and Gu Ye. All the members participated in the construction of wiki as they provided useful resources and beneficial suggestions.\\nPromotion Video \\nActors'},
   {'RosterName': 'Chang Liu',
    'RawTextName': 'Chang Liu',
    'TasksDescription': 'Art Design\\nShe is responsible for the art design of our team. She collaborates with Xinyi Xia in designing the team logo, uniform and artistic elements on our web pages. She is also involved in producing materials for educational activities. drafted the initial design of our hardware. Peripheral products related to our project was designed by Liu Chang and Xinyi. Xinyi and Liu Chang created plentiful artistic elements for the website. All the members participated in the construction of wiki as they provided useful resources and beneficial suggestions. \\nPromotion Video \\nArt Designing'},
   {'RosterName': 'Chengjun Yuan',
    'RawTextName': 'Chengjun Yuan',

In [6]:
# Remove \n, \\n, and multiple spaces between words from the attributions text
# Convert NaN values to None (supported by the JSON format)

def clean_json_data(json_data):

    for team in json_data:
        for team_name, members in team.items():
            for member in members:
                # Normalize TasksDescription
                tasks = member.get("TasksDescription")
                if isinstance(tasks, str):
                    cleaned = tasks.replace("\\n", " ").replace("\n", " ")
                    cleaned = re.sub(r"\s+", " ", cleaned)
                    member["TasksDescription"] = cleaned.strip()
                
                # Convert any NaN value in the member dict to None
                for key, value in member.items():
                    if isinstance(value, float) and math.isnan(value):
                        member[key] = None
    return json_data

In [8]:
json_test_data = clean_json_data(json_test_data)
json_test_data

[{'Aalto-Helsinki': [{'RosterName': 'Melissa Hendr�n',
    'RawTextName': 'Melissa Hendrén',
    'TasksDescription': 'is one of the team co-leads to the Aalto-Helsinki team. She is head of the wet-lab team and involved in fundraising, collaborations with other teams, writing, synbio and travelling organisation.'},
   {'RosterName': 'Veera Kurki',
    'RawTextName': 'Veera Kurki',
    'TasksDescription': 'is one of the team co-leads to the Aalto-Helsinki team. She is head of the human practices, the social media team and chair of synbio. She is part of the wet-lab and involved in fundraising, collaborations, writing, social media and travelling organisation.'},
   {'RosterName': 'Diogo Dias',
    'RawTextName': 'Diogo Dias',
    'TasksDescription': 'is head of the dry-lab. He is involved in the data analysis of the project, blogpost writing and review as well as participating in the development of the promotion video.'},
   {'RosterName': 'Amna Gul',
    'RawTextName': 'Amna Gul',
    'TasksDescription': 'is an active member of the wet-lab team. She contributes to the project in several ways, including through fundraising, collaborations, human practices, writing, and the production of a promotional video.'},
   {'RosterName': 'Lilith Heiland',
    'RawTextName': 'Lilith Heiland',
    'TasksDescription': 'is head of the writing team and part of the wet-lab team. She is involved in fundraising, collaborations, human practices, promotion video, and travel organisation.'},
   {'RosterName': 'Zsofia Hesketh',
    'RawTextName': 'Zsófia Hesketh',
    'TasksDescription': 'is head of the collaboration team and part of the wet-lab team. She is involved in writing, human practices, and travel planning.'},
   {'RosterName': 'Mari Keskiivari',
    'RawTextName': 'Mari Keskiivari',
    'TasksDescription': 'is head of the graphic design team and part of the wet-lab team. She is involved in writing, human practices, promotion video, social media, synbio, and travel organisation.'},
   {'RosterName': 'Anniina Könönen',
    'RawTextName': 'Anniina Könönen',
    'TasksDescription': 'is head of the fundraising team and part of the dry-lab team. She is involved in collaborations, writing, synbio and travel planning.'},
   {'RosterName': 'Joose Lankia',
    'RawTextName': 'Joose Lankia',
    'TasksDescription': 'is head of the promotion video team and part of the dry-lab team. He is involved in collaborations, programming, writing, human practices, graphic design, and the social media team.'},
   {'RosterName': 'Hanna Nebelung',
    'RawTextName': 'Hanna Nebelung',
    'TasksDescription': 'is head of the programming team and part of the dry-lab team. She is involved in collaborations, and human practices teams.'},
   {'RosterName': 'Heli Viskari',
    'RawTextName': 'Heli Viskari',
    'TasksDescription': "Heli is one of the principal investigators of the Aalto-Helsinki 2022 iGEM team. Her help has been crucial throughout our iGEM journey, by being present throughout the ideation phase and giving us feedback of how to progress. Additionally, the laboratory space at Aalto University was provided by Heli, and Heli has helped us actively with orders throughout the summer - even contributing some of her own teaching budget to the iGEM team. Furthermore, she gave us instructions on some simple lab tasks to ensure biosafety measures are in place in our group's work. Thank you very much Heli for all the dedicated work that you have provided to our iGEM team!"},
   {'RosterName': 'Markus Linder',
    'RawTextName': 'Markus Linder',
    'TasksDescription': 'Markus is one of the principal investigators of the Aalto-Helsinki 2022 iGEM team. He guided us through the brainstorming process and gave feedback to our initial ideas encouraging us to consider the combination of our potential earlier ideas. Furthermore, he approved together with Heli the additional financial support from the teaching budget to our iGEM team. We are very grateful for the help and guidance we received from you, Markus..'},
   {'RosterName': 'A. Sesilja Aranko',
    'RawTextName': 'Sesilja Aranko',
    'TasksDescription': 'Sesilja is one of the advisors of the Aalto-Helsinki iGEM 2022 team. She has helped the team in the initial ideation phase giving us advice, but was also essential during the realisation of the project in the lab. Sesilja provided help during the construction of the bioreporter and also in the initial stage of the DARPin library and was essential for providing us with information of the presence both location wise and stock wise of lab equipment and chemicals. Additionally, the team thanks you, Sesilja, for helping us develop a schedule for our lab work.'},
   {'RosterName': 'Ville Paavilainen',
    'RawTextName': 'Ville Paavilainen',
    'TasksDescription': 'Ville is one of the advisors of the Aalto-Helsinki 2022 iGEM team. His guidance was crucial throughout our ideation and brainstorming phase. We received valuable input from him throughout the ideation phase and also in setting up our lab protocols. Ville connected us to key contacts including Anja Paatero and Kah Ying Ng for checking our protocols for ribosome display. Additionally, he provided us lab space to work in to test our initial protocols. Ville, we thank you for your independable help in setting up the ribosome display.'},
   {'RosterName': 'Ilse Kaaja',
    'RawTextName': 'Ilse Kaaja',
    'TasksDescription': 'Ilse is one of the PhD mentors of the Aalto-Helsinki iGEM team. She has been very helpful during the beginning of the project, as she also has been a part of the Aalto-Helsinki iGEM team in 2019. We have got help with iGEM registry questions, and common questions we have had during our meetings with the mentors. We are very grateful for the support Ilse has given us during the project.'},
   {'RosterName': 'Juuso Taskinen',
    'RawTextName': 'Juuso Taskinen',
    'TasksDescription': 'Juuso is one of the PhD mentors of the Aalto-Helsinki iGEM team. He was essential in guiding us throughout our project by providing questions that made us think deeper and in more detail about our approaches. Additionally, Juuso was present to help with wet-lab questions that were too complicated for us to solve. We thank you very much for the impact you had on our project.'},
   {'RosterName': 'Sami Jalil',
    'RawTextName': 'Sami Jalil',
    'TasksDescription': 'Sami is one of the Phd mentors of the Aalto-Helsinki iGEM team. His help has been essential for the set up of our bioreporter. He reviewed with us the bioreporter and the integration of it into our plasmid. Furthermore, he provided us with the essential plasmid pET42b-HF-BE3 required for the expression of our GFP-DARPin, so that we could pass it to the Dresden iGEM team. We thank you, Sami, for the constant support that you showed our team.'},
   {'RosterName': 'Rishi Banerjee',
    'RawTextName': 'Rishi Banerjee',
    'TasksDescription': 'Rishi is one of the Phd mentors of the Aalto-Helsinki team. He was helpful in the beginning of the project for primer design. He provided online resources for primer design and annealing temperature calculations.'}]},
 {'Aboa': [{'RosterName': 'Pauli Kallio',
    'RawTextName': 'Pauli Kallio',
    'TasksDescription': "Our primary PI Pauli Kallio provided us with useful insight throughout our brainstorming process, which helped us direct our project's focus on detection systems. He also helped us with troubleshooting as well as supported us throughout the iGEM year."},
   {'RosterName': 'Juuli Hietarinne',
    'RawTextName': 'Juuli Hietarinne',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Juuli continued her last year’s iGEM journey as a team leader with Malin. They shared various organizational and guiding tasks, trying to teach as much as possible to new iGEMers and to ensure that all relevant criteria were met. In addition to her role as a team leader, she was also the head of Media. Juuli’s media-related tasks included, in addition to the organizational duties, creating social media content, writing a piece of news, and updating our own website. Besides, she actively participated in wiki coding and layout planning, fundraising activities, and promotion video planning. Juuli’s human practices -related responsibilities included for example planning and creating educational posts published on our social media accounts, creating other educational material for school visits, and taking part in some collaborations.'},
   {'RosterName': 'Malin Eriksson',
    'RawTextName': 'Malin Eriksson',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Malin continued her role as a team leader from last year and shared the task with Juuli. Together with Juuli she tried her best to share everything she had learnt from her iGEM 2021 experience to the new team to avoid repeating past mistakes and set the team up for success. This included, for example, organizational tasks and scheduling. Additionally, Malin helped the wet lab subteam get started, negotiated to get a laboratory for the team to work in, provided everyday support and advice to the lab team in the beginning of the summer, and actively led many collaboration and partnership meetings. She also had smaller roles within the team’s human practices and fundraising work, which included contributions to educational materials, interviews with stakeholders, and securing financial assistance from the university.'},
   {'RosterName': 'Anni Marjomaa',
    'RawTextName': 'Anni Marjomaa',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Anni was an active member in the wet lab subteam. In addition, she contributed to the educational materials for school visits as well as to educational posts published on our social media accounts. Anni was also arranging some of our integrated human practices meetings with farmers as well as participated in Heureka workshops, school visits, and the Study in Turku fair where we spread knowledge about iGEM and synthetic biology in general.'},
   {'RosterName': 'Evelina Ojaniittu',
    'RawTextName': 'Evelina Ojaniittu',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Evelina spent a whole summer in the lab doing our experiments. In addition, she contributed to educational posts published on social media and took care of our Facebook account in general. Evelina also participated in school visits, Heureka workshops, and the Study in Turku fair.'},
   {'RosterName': 'Iida Raaska',
    'RawTextName': 'Iida Raaska',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Our head of IT, Iida, was in charge of the coding of our wiki and she also took part in the creation of our own website. In addition to these responsibilities, Iida also contributed to dry lab work.'},
   {'RosterName': 'Jesper Mickos',
    'RawTextName': 'Jesper Mickos',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Jesper, our head of Wet Lab, planned the majority of our experiments and organized our lab work. He participated in both wet lab and dry lab -related collaborations and partnerships and troubleshooting actively. In addition to the wet lab, Jesper also contributed to fundraising and human practices activities, such as the Study in Turku fair and the Science Basement talk.'},
   {'RosterName': 'Jonna Pohjankukka',
    'RawTextName': 'Jonna Pohjankukka',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Jonna actively participated in fundraising, wet lab, and human practices activities. She created some social media content for Instagram and was in charge of our LinkedIn account. Jonna also contributed to the educational content for school visits and visited one school. In addition to this, she participated in the Heureka workshops for kids and in the Study in Turku fair, where we told other students about our project and iGEM. Jonna was involved in many of our collaborations and partnerships and you can also hear her voice in our promotion video.'},
   {'RosterName': 'Kevät Sova',
    'RawTextName': 'Kevät Sova',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Kevät was the head of Human Practices. Alongside their responsibility as a subteam leader, they participated actively in the wet lab subteam by working in the summer. Additionally, they used their artistic creativity to participate in the Synbio-themed art journal made by the iGEM team ASU. They also arranged school visits, interviewed various researchers and farmers, and participated in the Study in Turku fair.'},
   {'RosterName': 'Kristiina Keski-Oja',
    'RawTextName': 'Kristiina Keski-Oja',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Kristiina was the treasurer of the Aboa Turku ry, the organization behind our team. Thus, all money-related things were her responsibility. She was also an active member of the wet lab subteam, as well as participated in human practices and fundraising activities.'},
   {'RosterName': 'Minttu Turunen',
    'RawTextName': 'Minttu Turunen',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Minttu was our head of Visual Design, and her main responsibility was the planning, filming, and editing of our amazing promotion video. In addition, she took multiple photos for our wiki, participated in the planning of our wiki layout, and contributed to educational posts published on our social media accounts.'},
   {'RosterName': 'Nelli Heiskanen',
    'RawTextName': 'Nelli Heiskanen',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Nelli was our head of Fundraising. Her duties as a subteam leader consisted of planning the strategies for fundraising, such as contacting possible sponsors, creating value for the sponsors, creating presentation materials, and organizing meetings. Alongside her responsibility as a subteam leader, she created social media content as well as educational material for our school visits. She also contributed to the promotion video planning and acting, as well as participated in some other activities, such as the Science Basement talk.'},
   {'RosterName': 'Otto Rydman',
    'RawTextName': 'Otto Rydman',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Otto was a wet lab subteam member and also participated in multiple human practices activities, including stakeholder interviews. Furthermore, he contributed to the planning of our promotion video and was the main film star in it.'},
   {'RosterName': 'Sini Kylä-Kaila',
    'RawTextName': 'Sini Kylä-Kaila',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Sini was the chairperson of Aboa Turku ry, the organization behind our team. She also contributed to fundraising, visual design, and media activities in the spring.'},
   {'RosterName': 'Sofia Antin',
    'RawTextName': 'Sofia Antin',
    'TasksDescription': 'All team members participated in the general activities, such as brainstorming and wiki writing. Sofia participated in the wet lab work.'}]},
 {'BostonU_HW': [{'RosterName': 'Diana Arguijo',
    'RawTextName': 'Diana Arguijo',
    'TasksDescription': 'Microfluidic Device Design Microfluidic Device Diagnostics Technical Support Lab Maintenance'},
   {'RosterName': 'Hailey Lenn Gordon',
    'RawTextName': 'Hailey Lenn Gordon ',
    'TasksDescription': 'Outreach Coordinator Social Events Coordinator Technical Support Fundraising Human Practices Coordinator'},
   {'RosterName': 'Douglas Densmore',
    'RawTextName': 'Douglas Densmore',
    'TasksDescription': 'Team Coordinator Technical Support'},
   {'RosterName': 'Alexander Barutis',
    'RawTextName': 'Alex Barutis',
    'TasksDescription': 'Background Research Incubator Design Commercial Web App Development Modeling Documentation Wiki'},
   {'RosterName': 'Aya Kassem',
    'RawTextName': 'Aya Kassem',
    'TasksDescription': 'Background Research Pressure System Incubator Web App Development System Automation Microfluidic Fabrication Electronic Managment'},
   {'RosterName': 'Julia Nowak',
    'RawTextName': 'Julia Nowak',
    'TasksDescription': 'Background Research Aquatic Environment Commercial Documentation Microfluidic Fabrication Documentation Safety'},
   {'RosterName': 'Stephen Sweet',
    'RawTextName': 'Stephen Sweet',
    'TasksDescription': 'Background Research Sampling System Pressure System Documentation Electronic Management Housing'},
   {'RosterName': 'zakir kadwa',
    'RawTextName': 'Zakir Kadwa',
    'TasksDescription': 'Background Research Aquatic Environment Housing Modeling Documentation'}]},
 {'CPU_Nanjing': [{'RosterName': 'Jingzhi Hu',
    'RawTextName': 'Jingzhi Hu',
    'TasksDescription': 'In the initial design and later practice of our project, both Dr. Xin Wang and Dr. Jingzhi Hu gave us many constructive suggestions, which made our project go smoothly.'},
   {'RosterName': 'Hai Qian',
    'RawTextName': 'Hai Qian',
    'TasksDescription': 'Without his help, we cannot complete our project.'},
   {'RosterName': 'Xin Wang',
    'RawTextName': 'Xin Wang',
    'TasksDescription': 'In the initial design and later practice of our project, both Dr. Xin Wang and Dr. Jingzhi Hu gave us many constructive suggestions, which made our project go smoothly.'},
   {'RosterName': 'Mayu Shan',
    'RawTextName': 'Mayu Shan',
    'TasksDescription': 'Student Leader As the leader of CPU_Nanjing, he is responsible for the overall management of team affairs and the coordination of different departments. He is involved in HP design and organizes field visits, hardware construction and education activities. participated in the construction of the hardware to verify the feasibility of manufacturing phosphate from materials available on terrestrial planets. was in charge of organizing field visits and producing online education materials together with Tianchang and Gu Ye. All the members participated in the construction of wiki as they provided useful resources and beneficial suggestions. Promotion Video Actors'},
   {'RosterName': 'Chang Liu',
    'RawTextName': 'Chang Liu',
    'TasksDescription': 'Art Design She is responsible for the art design of our team. She collaborates with Xinyi Xia in designing the team logo, uniform and artistic elements on our web pages. She is also involved in producing materials for educational activities. drafted the initial design of our hardware. Peripheral products related to our project was designed by Liu Chang and Xinyi. Xinyi and Liu Chang created plentiful artistic elements for the website. All the members participated in the construction of wiki as they provided useful resources and beneficial suggestions. Promotion Video Art Designing'},
   {'RosterName': 'Chengjun Yuan',
    'RawTextName': 'Chengjun Yuan',
    'TasksDescription': 'Presentation Member He is in responsible of team presentation. He is also in charge of translating materials into English and dubbed team promotion video. His strong English ability contributes a lot to our project. All the members participated in the construction of wiki as they provided useful resources and beneficial suggestions. Promotion Video Dubbed by Narration Writers'},
   {'RosterName': 'Haotian Liu',
    'RawTextName': 'Haotian Liu',

In [9]:
with open("../data/attributions/2022_attributions/manual_annotation/14_test_teams.json", 'w', encoding='utf-8') as f:
    json.dump(json_test_data, f, ensure_ascii=False, indent=2)

### 2.2 Validation (Prompt Engineering) Teams

To refine our prompt, we selected 6 surveyed teams that either do not have an iGEM website folder or are missing their attributions `.txt` or `.html` file (check out `6_match_teams_2022_attributions.ipynb` for details). Their task attributions were collected manually from their GitLab repositories. The reason they were not previously included in the extraction of attribution texts alongside other teams is that their attributions were mostly written in JavaScript and not HTML files. However, one team is removed because it did not list any performed tasks on its Attributions webpage, so there are 5 validation teams left.

In [11]:
# Load manually annotated tsv attributions
# One team is also present in the 14 random teams because it was noticed that its attributions were written in an unreadable table
# For this team, the attributions were manually extracted from the iGEM wiki page
# The team is dropped from the validation test and used only for the random teams evaluation

df_manual_validation_attributions = pd.read_csv("../data/attributions/2022_attributions/manual_annotation/7_teams_members_descriptions_from_wikis.tsv", sep="\t")

df_manual_validation_attributions = df_manual_validation_attributions[
    ~df_manual_validation_attributions["Team"].isin(["Sogang_Korea", "HKU-HongKong"])
]

In [47]:
df_manual_validation_attributions

,RawTextName,RosterName,Team,TasksDescription,Comments
21,Óscar Ariel Rojas Rejón,Oscar Rojas-Rejon,ITESO_Guadalajara,for his constant support throughout the compet...,NaN
22,Sarah Ratkovich Gonzalez,Sarah Ratkovich-Gonzalez,ITESO_Guadalajara,for her unconditional support as our Principal...,NaN
23,Cristóbal Camarena Bernard,Cristobal Camarena,ITESO_Guadalajara,"for being our contact with the university, for...",NaN
24,Claudia Denisse Valdés Michel,Claudia Valdes,ITESO_Guadalajara,For her amazing work as the team leader and as...,NaN
25,Sofía Carolina Bárcena Pérez,Sofia Carolina Barcena Perez,ITESO_Guadalajara,For her outstanding work as responsible for La...,NaN
...,...,...,...,...,...
125,Gabrielė,Gabriele Olendraite,Vilnius-Lithuania,Protein expression optimisation and purificati...,NaN
126,Laura,Laura Milaknytė,Vilnius-Lithuania,Hardware. The 6th SynBio Sense. Baltic Jambore...,NaN
127,Simona,Simona Bendziute,Vilnius-Lithuania,National Television LRT. Marketing. Baltic Jam...,NaN
128,Simonija,Simonija Kelpsaite,Vilnius-Lithuania,Plasmid vector contruction. Peptide affinity e...,NaN
129,Vadimas,Vadim Čeremisinov,Vilnius-Lithuania,Software. The 6th SynBio Sense. Wiki design. W...,NaN

In [12]:
# Convert to JSON format as well

json_validation_data = convert_df_to_json_format(df_manual_validation_attributions)

In [13]:
# Clean the JSON data
json_validation_data = clean_json_data(json_validation_data)

In [15]:
with open("../data/attributions/2022_attributions/manual_annotation/5_validation_teams.json", 'w', encoding='utf-8') as f:
    json.dump(json_validation_data, f, ensure_ascii=False, indent=2)